### ISSUE TITLE
As a Team We want to setup cloud test environment for Shopware-PWA So we can work and test together

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#1]
**Context**
In the beginning of the project we want to setup shared test environment. We want to use Divante's technology for that, which allows us to host that in a cloud.

**Acceptance Criteria**
- Test environment is running in Divante VueStorefront Cloud.
- Test environment is available under domain shopware-pwa.storefront.io.
- Documentation describes how to access test environment. For now it should be in Confluence: https://divante.atlassian.net/wiki/spaces/SHOP/pages/1479049282/Test+environment
- Test environment is **not** secured by password.
- `DivanteLtd/shopware-pwa` is pulled to test environment.
- @patzick can access test environment.
- @rmakara can access test environment.
- @mkucmus can access test environment.

**Comment by rmakara** [comment]
Test of Slack integration with `shopware-pwa` Github repository.

**Comment by rmakara** [comment]
Test of Slack integration with `shopware-pwa` repository.

**Comment by mkucmus** [comment]
Test env has been created. Credentials were stored at the confluence.
