### ISSUE TITLE
[default-theme][bug] Post-css warning fill-available

### ISSUE THREAD

**Issue by Rigo-m** [DivanteLtd/shopware-pwa#1009]
https://github.com/DivanteLtd/shopware-pwa/blob/5aeb651e3161d0f4e670b375dd0153288ccab581/packages/default-theme/cms/blocks/CmsBlockProductThreeColumn.vue#L71

Post-css warns about `fill-available` being replaced by `stretch`. Is there any reason why fill-available has been used?

@mkucmus

**Comment by mkucmus** [comment]
@Rigo-m thanks, we will fix it soon :+1:
