### ISSUE TITLE
Handle nested associations in searchConverter

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#103]
**Context**
In PR #102 @patzick implemented associations. All the stuff work in that PR work very well. 

We found one more requirement to cover the use case of adding nested associations.

Dominic provided us with following example:
```
product/7b7a3457a26d4919ad94897d61e1dc6e?associations[properties][associations][media][]=1
```

and also there is a following JSON format:

```
"associations": {
  "media": {
    "associations": { "product": {} } 
    }
}
```
which adds association for category -> media -> product.

**Acceptance Criteria**
* searchConverter allows developers to add nested associations.
* It is possible to add 1st level associations.
* It is possible to add 2nd level associations.
* It is possible to add 3nd level associations.

**Comment by patzick** [comment]
@rmakara done with #123
