### ISSUE TITLE
Unable to get shopware-pwa running on local

### ISSUE THREAD

**Issue by ankur-moovweb** [DivanteLtd/shopware-pwa#1062]
### Describe the bug
I am trying to run the shopware-pwa on the local system, using the default configuration.

### Steps:
Follow the steps on the github page
* npm install -g @shopware-pwa/cli
* mkdir my-shopware-pwa
* cd ./my-shopware-pwa
* shopware-pwa init
* shopware-pwa dev

### Issue
 ERROR  [Vue warn]: Failed to resolve async component: () => __webpack_require__.e(/*! import() */ 3).then(__webpack_require__.bind(null, /*! @shopware-pwa/default-theme/components/views/CategoryView */ "./node_modules/@shopware-pwa/default-theme/components/views/CategoryView.vue"))
Reason: Error: Module parse failed: Unexpected token (25:26)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     cmsSections() {
|       console.log(this);
>       return this.content?.sections || [];
|     }
| 

![image](https://user-images.githubusercontent.com/69921416/91726264-d154d780-eb54-11ea-866e-b1d06f1068c0.png)

![image](https://user-images.githubusercontent.com/69921416/91726333-ecbfe280-eb54-11ea-8fbf-04b73c434945.png)

**Comment by dvdmlln** [comment]
I had exactly the same problem, it didn't run on my local windows system.
Then I tried the virtual machine (ubuntu 20.04) where I ran shopware and it worked. I installed nodejs and npm using the package manager.
So I tried setting up a new virtual machine, only installed nodejs with the same version I ran on the shopware system but this time I used nvm to install node and it didn't work.
Using the package manager to install nodejs and npm it also worked with wsl.

**Comment by Malwurf** [comment]
@ankur-moovweb 
@dvdmlln 
Thanks for your notification.

I checked twice setting a local environment and everything works fine. Checked on native ubuntu 20.04 / Node.js v12.16.2 / 6.14.4.

We just released version 0.4.0 which has some fixes and new features. Please remove your currently non-working Shopware-PWA instance and install it again using the current version.

**Comment by ankur-moovweb** [comment]
Was able to run the shopware-pwa on local. Thanks for the update.
I did need to delete, and start with a fresh install, but that is most probably due to a mis-configuration on my end.
Thanks
