### ISSUE TITLE
BUG: Error overwriting SwProductListingFilters

### ISSUE THREAD

**Issue by niklaswolf** [DivanteLtd/shopware-pwa#1088]
### Describe the bug
Trying to overwrite `SwProductListingFilters.vue` via `shopware-pwa overwrite` results in the error `SassError: File to import not found or unreadable: ../cms/settings.scss.`
I assume this import should be done via Alias or removed/refactored completely.

### Additional context
https://github.com/DivanteLtd/shopware-pwa/blob/e296bea203ea19d3d3a769e0625e0a954fa5b9ed/packages/default-theme/components/SwProductListingFilters.vue#L203

**Comment by patzick** [comment]
Thanks!
Fix for that is to find all relative paths in components and replace that with home alias
so for example in cms folder all `@import "../settings.scss";` should be `@import "@/cms/settings.scss";` etc

As for Niklas example it should be `@import "@/cms/settings.scss";` as well

## Acceptance criteria
- [ ] all relative paths inside components are resolved with `@` alias as above

**Comment by niklaswolf** [comment]
I'll provide a PR for that next week :)

**Comment by patzick** [comment]
@niklaswolf yeah, you're right that's true on the current stable version

but with near 0.4 release, current master brings some structure changes, thanks to this we're preparing the project for themes inheritance
more info about those changes here: https://shopware-pwa-docs.vuestorefront.io/landing/getting-started/upgrade.html#migrate-version-0-3-x-to-0-4-x

so to summarize - on your project you need alias with `default-theme` but in PR to master examples above will be already adjusted to upcoming changes :)

**Comment by patzick** [comment]
Thanks @niklaswolf ! :)
