### ISSUE TITLE
Google Analytics tracking in CLI

### ISSUE THREAD

**Issue by niklaswolf** [DivanteLtd/shopware-pwa#1090]
I just stumbled upon the following:
https://github.com/DivanteLtd/shopware-pwa/blob/e296bea203ea19d3d3a769e0625e0a954fa5b9ed/packages/cli/src/commands/override.ts#L61

Guys is it really necessary for you to track these kind of things silently to Google Analytics?

**Comment by andreasemer** [comment]
Please ask a lawyer if this tracking is GDPR compliant, that would surprise me very much.
