### ISSUE TITLE
[BUG] Text Elements are not displayed - Canary Version

### ISSUE THREAD

**Issue by jonaletil** [DivanteLtd/shopware-pwa#1092]
### Describe the bug

Text Elements are not displayed in frontend, 

###  Steps to reproduce:
- open shopping experiences
- choose any block with text element
- check the frontend

### Admin Area
![admin](https://user-images.githubusercontent.com/39805796/92946030-66f63e00-f456-11ea-9e7a-67bf4ccd46ae.png)
### Frontend Area 
Text Elements are not visible, just the image elements
![frontend](https://user-images.githubusercontent.com/39805796/92946183-94db8280-f456-11ea-8c91-0ab39d045020.png)

**Comment by Malwurf** [comment]
Hello @jonaletil ! Thanks for your issue. Problably we fxed t via [FIX-1065](https://github.com/DivanteLtd/shopware-pwa/issues/1065). Can You checked this issue again?

**Comment by mkucmus** [comment]
We are closing the issue because it was fixed and no further issue related to this were reported :)
