### ISSUE TITLE
[BUG] Cannot create a new account

### ISSUE THREAD

**Issue by alexschwarz89** [DivanteLtd/shopware-pwa#1109]
### Describe the bug
When trying to register with any email address, i get the error "Cannot create a new account, the user may already exist". In error console there is a 400 error visible. Shopware 6 plain installation + pwa-plugin running on a remote server, shopware-pwa running locally. 

This error does also happen on the demo instance here: https://shopware-pwa.storefrontcloud.io/

```
* errors: [{code: "VIOLATION::NO_SUCH_CHOICE_ERROR", status: "400", title: "Constraint violation error",…}]
    * 0: {code: "VIOLATION::NO_SUCH_CHOICE_ERROR", status: "400", title: "Constraint violation error",…}
        * code: "VIOLATION::NO_SUCH_CHOICE_ERROR" detail: "The value you selected is not a valid choice." meta: {,…}
            * parameters: {{{ value }}: ""http://192.168.1.66"", {{ choices }}: ""http://domain-of-server.com""}
                * {{ choices }}: ""http://domain-of-server.com"" {{ value }}: ""http://192.168.1.66"" 
        * source: {pointer: "/storefrontUrl"}
            * pointer: "/storefrontUrl" 
        * status: "400" title: "Constraint violation error
```

How to reproduce?
- Install a naked shopware 6 (latest stable; 6.3.1.0)
- Install the plugin to connect with shopware-pwa
- Configure storefront url
- Install shopware-pwa with latest stable 
- Try to add a new user 

### Additional context
Local machine running OS X 10.15.6
Node v12.18.4
Nuxt.js @ v2.14.5  

on the remote:
Shopware 6.3.1.0 / PHP 7.4 / MySQL 8

**Comment by mkucmus** [comment]
thanks @alexschwarz89 for the issue!

It looks like a configuration problem, 
the storefrontUrl should match the one in your sales channel domains configuration.
the **storefrontUrl** parameter is taken like that:
```
storefrontUrl:
          window &&
          window.location &&
          `${window.location.protocol}//${window.location.hostname}`,
```

so all you need to do is to create an appropriate entry in the domain list within the sales-channel config you are connecting with.

btw. I added one and that fixed the issue in the demo instance you mentioned above:
![image](https://user-images.githubusercontent.com/5596960/93741989-a3136680-fbed-11ea-93bd-6fd51e2abf28.png)

hope it helps, take care!
