### ISSUE TITLE
[BUG] No menu on canary

### ISSUE THREAD

**Issue by alexschwarz89** [DivanteLtd/shopware-pwa#1110]
### Describe the bug
There is no menu even on the canary builds on first page load (https://shopware-pwa-canary.storefrontcloud.io/). If you go to detail pages the menu randomly appears.

Browser: Latest Chrome on OS X

**Comment by mkucmus** [comment]
@alexschwarz89 it's already done. one minute ago we updated the master with the upcoming's release
