### ISSUE TITLE
[BUG] PersonalDetailsGuestForm is not working when creating a new account

### ISSUE THREAD

**Issue by fsavina** [DivanteLtd/shopware-pwa#1125]
`this.customer` is `undefined` in the `toShipping` method in `PersonalDetailsGuestForm.vue` causing a bug when you try to access the shipping step while creating a new account

https://github.com/DivanteLtd/shopware-pwa/blob/e729c2407c09d7928719c0c8eeb01f7313524fba/packages/default-theme/components/checkout/steps/guest/PersonalDetailsGuestForm.vue#L278

**Comment by fsavina** [comment]
shopware-pwa version: canary
SW version: v6.3.0.2

**Comment by mkucmus** [comment]
@fsavina is it still an issue? I have checked it today, but the shopware-pwa@canary is too new I guess, and it just does not happen

**Comment by fsavina** [comment]
Honestly, I've no idea. We haven't been upgrading the shopware-pwa package for weeks now because we've overridden 2/3 of the code and there's no point in upgrading it anymore

**Comment by fsavina** [comment]
@mkucmus feel free to close the ticket if you are not able to reproduce the bug. I've fixed it in my overriden component

**Comment by mkucmus** [comment]
thanks for the feedback, @fsavina one more thing: is it possible to list the main reasons why you override 2/3 of the code? Is the project you are currently working on that customized or the default-theme is not what you want at all ? ;)

**Comment by fsavina** [comment]
No worries.
I don't recall all of the reasons but some of them are:
- most of the texts are hardcoded in the components and we needed to move them to the snippets in order to translate them;
- several calls to the API in the shopware client are not customizable;
- some features where not implement (ie. adding a promotion code to the cart in the checkout steps);
- the lack of use of Vue slots in the components to customize their layout (storefront-ui components instead offer a great degree of customizability);
- some unresolved bugs like the one in this ticket;
