### ISSUE TITLE
[FEATURE] theme inheritance

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#1158]
### Acceptance criteria

- [x] it's possible to change the theme by providing its path 
- [x] the new theme can be built on top of the default-theme - building mechanism
- [ ] docs are updated

**Comment by ArjanStudent** [comment]
How many changes would the capybara theme need from vue-storefront to work in shopware PWA?

**Comment by mkucmus** [comment]
documentation closed via #1264
