### ISSUE TITLE
[BUG] JS error when changing window size

### ISSUE THREAD

**Issue by niklaswolf** [DivanteLtd/shopware-pwa#1162]
### Describe the bug
When changing the window size from desktop to mobile or vice versa, a Javascript error shows up in the browser console
```
Uncaught TypeError: observer is null
    onMediaMatch mobile-observer.js:5
    setupListener mobile-observer.js:18
    get mobile-observer.js:45
```
Seems to come from storefront-ui (at least mobile-observer.js is from storefront-ui) but I'm not quite sure.

**Comment by mkucmus** [comment]
@niklas-wolf is it still an issue? I cannot reproduce it now :)

**Comment by niklaswolf** [comment]
You are right, I can not reproduce it anymore in the core, but it's still an issue in our application. Apparently it's caused by `SfHeader` but that's our own problem now I think :D
