### ISSUE TITLE
[BUG] [helpers][getListingAvailableFilters][getFilterType]: Error: Unrecognized type | properties

### ISSUE THREAD

**Issue by abvdveen** [DivanteLtd/shopware-pwa#1195]
These errors appear in console, when requesting a page:

[helpers][getListingAvailableFilters][getFilterType]: Error: Unrecognized type | properties
[helpers][getListingAvailableFilters][getFilterType]: Error: Unrecognized type | option

Is this related to #1194?

**Comment by abvdveen** [comment]
This seems to have been fixed in latest canary. I also had the problem that 'sort' param was undefined, causing the paging on product listing to give 404 - also fixed in latest.

**Comment by mkucmus** [comment]
@abvdveen the way we extract the filters and deal with them has been changed recently. The complexity was reduced to a minimum. the upcoming 0.5.0 will be much more stable. Shall I close the issue?
