### ISSUE TITLE
I want to use Preview in Shopware Page Builder So I can see the final page styled with Shopware-PWA

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#121]
**Context**
In Shopware there is a Page Builder, that all the customers will use to create CMS pages. Right now we are not 100% sure if Page Builder will show all the components styled with StorefrontUI. It is possble that customers will build the CMS Pages without seeing the final result with StorefrontUI styles.

We want to generate the pages to let Shopware add button "Show Headless Preview" in Page Builder, which will link the user to generated page.

**Comment by patzick** [comment]
@elkmod I'm assigning you as you already on this :)
