### ISSUE TITLE
[BUG] Handle invalid combinations of options

### ISSUE THREAD

**Issue by elkmod** [DivanteLtd/shopware-pwa#1210]
### Describe the bug

Let's say I create a product with multiple variant dimensions like *color* and *size*.

However, some combinations (medium-green and large-blue) don't exist.

|dim|red|green|blue|
|--- | --- | ---| ---|
|**small**|X|X|X|
|**medium**|X|-|X|
|**large**|X|X|-|

If I have such a configuration, it breaks the variant switch when I try to switch to an invalid option. We've also observed cases, where it just falls back to the default product, if no corresponding variant is found.

### Expected behavior

Disable the options which are not valid starting from the current configuraiton.

**Comment by mkucmus** [comment]
closed via #1215
