### ISSUE TITLE
[FEATURE] Allow disconnect of existing interceptors

### ISSUE THREAD

**Issue by niklaswolf** [DivanteLtd/shopware-pwa#1247]
### Description
For some interceptors anonymous functions are used as callbacks to the `intercept` function. The problem with this approach is, that it's impossible to disconnect them afterwards, as the `disconnect` function (see [here](https://github.com/DivanteLtd/shopware-pwa/blob/872782191be055ab953a2ec9ec0fb42ea0762004/packages/composables/src/logic/useIntercept.ts#L88)) expects the callback function used as a second argument and there is no possibility to get the reference of the anonymous function used in `intercept`.

Example for this usecase are the notifications registered in [notifications.js](https://github.com/DivanteLtd/shopware-pwa/blob/master/packages/default-theme/src/plugins/notifications.js).
Right now it's impossible to disconnect for example the add-to-cart notification which should definitely be possible.

A good approach could be to use named functions for the interceptor callbacks and export them. Like this one could import them for example in another plugin and disconnect single interceptor-functions.

### Acceptance criteria
- [ ] it is possible to disconnect single interceptors for example in another nuxt plugin

**Comment by mkucmus** [comment]
Great! I agree we need to provide a more extensible API of useInterceptor composable... unfortunately when it comes to comparing anonymous function it does .toString on the method so practically impossible to find and disable such function.

**Comment by niklaswolf** [comment]
I think this can be closed now since the code was merged :)

**Comment by mkucmus** [comment]
> I think this can be closed now since the code was merged :)

you are right ;) in further PRs, please add the "closes: #xxx" sentence in the comment, and will be closed after the merge atumatically :+1:

**Comment by niklaswolf** [comment]
I know, in all other PRs I've done it, apparently I forgot in this one.
