### ISSUE TITLE
[BUG] Dev-Mode hardcoded in build-script

### ISSUE THREAD

**Issue by niklaswolf** [DivanteLtd/shopware-pwa#1250]
### Describe the bug
Currently when you run `yarn build` you'll always end up in devMode (PluginSlotSwitcher in footer enabled) because it is hardcoded to `true` in the build-command...
https://github.com/DivanteLtd/shopware-pwa/blob/3c715e422073ea820b5180dc7f29b2f607bba399/packages/cli/src/commands/build.ts#L15

**Comment by niklaswolf** [comment]
If it's hardcoded, it should be `false`, shouldn't it? :D 
I mean hardcoding it in the production-build script to `false` should be ok?

**Comment by niklaswolf** [comment]
Went with the "premium solution" and added a cli parameter to opt in to use dev mode.

**Comment by develth** [comment]
Hello,
cant turn it off - whats the exakt call?
Updated yesterday to 0.7.x and did a `npx @shopware-pwa/cli@canary init` - in this steps also set devMode to false. But it still appears.

**Comment by niklaswolf** [comment]
@develth did you run `yarn build && yarn start`? The production build should have `devMode` to false by default now, that was the fix in this ticket. When using the dev-server with hot reloading, the `devMode` defaults to true.

**Comment by develth** [comment]
@niklaswolf thanks for that information. And yes - did a yarn build, but currently running yarn dev. Was confused because i configured devMode to false on reinit
