### ISSUE TITLE
Start using prefetch hooks

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#151]
**Context**
Adding that task just to remember, that we have a dependency on composition-api.

**Dependencies**
* https : // github.com / vuejs / composition-api / pull / 80

**Comment by pkarw** [comment]
https://github.com/vuejs/composition-api/pull/80/files - seemingly it has been done on the branch

**Comment by rmakara** [comment]
Commit was made on on Aug 24. @filrak bumped it in the comment on Nov 6.
