### ISSUE TITLE
I want to see the discounts in the category page So I can be attracted by lower prices

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#18]
**Context**
We may have Cart Price Rules and Catalog Price rules, which affect the price. The second ones might be displayed in the category page. We should be able to see these discounts in the category page.

The way of displaying it (just smaller range, strikethrough original price etc.) needs to be discussed.

**Acceptance criteria**
* When the product has some Catalog Price Discount then I can see that in a Catalog Page.
* When I add the product to the cart then I can see discounted price in a cart.

**Comment by patzick** [comment]
done
