### ISSUE TITLE
Use SfHeader component for top navigation

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#184]
**Context**
Currently we have beautiful and the most preety-awesome menu made by @mkucmus . We would like to style it with SfHeader component, that was merged to Storefront UI today. In the next steps, we will use Mega Menu component from Storefront UI for hovering the SfHeader.

**Dependencies**
* https://github.com/DivanteLtd/storefront-ui/pull/450#event-2849078511

**Acceptance Criteria**
* SfHeader is used.
* Whole level 0 of top menu is being displayed.

**Next tasks**
* #8 Navigation, Mega Menu

**Comment by preeti0109** [comment]
Hello dear i want to customise top navigation and i want to put logo in between in top navigation please guide me how to do this.
Thanks for quick response. ****
