### ISSUE TITLE
I want to use Block View and List View in Category Page So I can customize the view up to my needs

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#202]
to refine

**Comment by patzick** [comment]
![image](https://user-images.githubusercontent.com/13100280/80476498-c4c43680-894a-11ea-98f5-2196428bf180.png)


## Acceptance criteria:
- [ ] implement switch behaviour from https://storybook.storefrontui.io/?path=/story/pages-category--common

**Comment by patzick** [comment]
related: #405

**Comment by patzick** [comment]
duplicated #655
