### ISSUE TITLE
Components appear on top of the Login Modal Window

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#206]
**Reference Storefront UI issue**
https://github.com/DivanteLtd/storefront-ui/issues/555

**Current behavior** 
When I am in the Product Page and I open login popup then components overlap with invalid z-indexes.

![shopware invalid zindex](https://user-images.githubusercontent.com/1880231/70778145-db923400-1d81-11ea-8ea3-e77ad2877e98.jpg)

**Expected behavior**
Modal window of Login Panel should appear on top.

**Comment by rmakara** [comment]
@akrajna @krskibin 
Is it done? :)

**Comment by akrajna** [comment]
Works fine :-)
