### ISSUE TITLE
Fix the header 

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#243]
Scope:
- logo in TopNavigation should fit in size to the whole element
![Screenshot_2020-01-14 https shopware-pwa-faint-money now sh](https://user-images.githubusercontent.com/12700136/72360137-d103eb00-36ef-11ea-9ab4-d4dffb19458f.png)
- cart badge should be the same as logged user badge (now is custom)
![Screenshot_2020-01-14 https shopware-pwa-faint-money now sh(1)](https://user-images.githubusercontent.com/12700136/72360384-2a6c1a00-36f0-11ea-9775-00db4f6d0e89.png)

**Comment by mkucmus** [comment]
Cart badge isn't available yet. Issue reported: https://github.com/DivanteLtd/storefront-ui/issues/654

**Comment by rmakara** [comment]
@mkucmus @patzick @krskibin 
This task is On Hold but probably it's been already fixed? If this is correct then please close. :)
