### ISSUE TITLE
Test all the CMS components from Shopware Shopping Experiences

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#250]
**Acceptance Criteria**
* All the components available in Page Builder is tested. If these components are being rendered in the Shopware PWA layer.
* List of the components is prepared to we can place that in README.MD of CMS Package.

**Useful links**
* https://github.com/DivanteLtd/shopware-pwa/issues/129 Original task about preparation of CMS Components

**Comment by akrajna** [comment]
@mkucmus 
List of the CMS components from Shopware Shopping Experiences:
1. Text Block category
   1. Text
   2. Text banner
   3. Teaser text
   4. Two columns, teaser text
   5. Two columns, text
   6. Three columns, text
2. Images Block category
   1. Image, boxed
   2. Image, full-sized
   3. Two columns, boxed
   4. Three columns, boxed
   5. Three columns, full-sized
   6. Four columns, boxed
   7. Three columns, rounded
   8. Three columns, boxed & background
   9. Image grid
   10. Image slider
   11. Image gallery
3. Video Block category
   1. YouTube video
   2. Vimeo video
4. Text&images Block category
   1. Two columns, boxed image & text
   2. Two columns, full-sized image & text
   3. Three columns, boxed images & text
   4. Three columns, captioned images
   5. Three columns, image/text cards
   6. Three columns, captioned & rounded
   7. Hero image
5. Commerce Block category
   1. Three columns, product boxes
   2. Product slider
6. Sidebar Block category
   1. Product filter
   2. Category navigation
7. Form Block category
   1. Form
