### ISSUE TITLE
Create endpoint with the Assets

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#255]

**Comment by elkmod** [comment]
Could be coalesced with the command described in #254 and produces a compressed output artifact of the directory format outlined below.

```
.
swag-hello-dolly/
  index.js
  components/
  pages/
swag-paypal-pwa/
   index.js
   components/
   pages/
```

**Comment by patzick** [comment]
@elkmod  Yeah, this looks exactly like it should :)
Will be in #254 listed every one of these files? Or id could be not necessary, wdyt?

**Comment by rmakara** [comment]
Possible to be mocked by @patzick

**Comment by elkmod** [comment]
PR in https://github.com/elkmod/SwagVueStorefront/pull/33, providing `bin/console pwa:dump-plugins` command, which creates a `pwa-bundles.json` containing configurations and `pwa-bundles-assets.zip` containing all plugins with their corresponding asset files collected from their respective `Resources/app/pwa` directories.
