### ISSUE TITLE
Checkout -> Redirect to PWA

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#261]

**Comment by elkmod** [comment]
Once the order is finished, create a redirect to the PWA application. Attach the ID of the created order so that it can be displayed on the order success page.

Currently WIP - https://github.com/elkmod/SwagVueStorefront/pull/31

**Comment by elkmod** [comment]
Also currently waiting for corresponding order endpoint to fetch the order.
We could just attach serialized order information to the link in the meantime, so we can display an order summary. @rmakara

**Comment by elkmod** [comment]
Proposing to close this due to different prioritization.
