### ISSUE TITLE
Checkout -> Order (thank you page) endpoint

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#262]
Get order for a success token

**Comment by elkmod** [comment]
![image](https://user-images.githubusercontent.com/7780750/79966861-571d9380-848e-11ea-92b0-381dcd359f8c.png)

Implemented in store-api (as of current master and from 6.2) - endpoint to fetch orders for current user based on arbitrary criteria.

**Comment by patzick** [comment]
will be continued in #664
