### ISSUE TITLE
Fix - Register many users with the same email address

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#266]

**Comment by rmakara** [comment]
Fixed in Shopware 6.
To test on our side.

**Comment by rmakara** [comment]
@akrajna 
Help. :)

**Comment by akrajna** [comment]
It is not possible to create an account with already existing email address but user does not get any information about it.
![RegisterExistingEmail](https://user-images.githubusercontent.com/57936972/76408604-7d2f1e80-638d-11ea-89e6-e143de33fdfa.png)

User should be informed that a customer with the same email already exists e.g.
![customerExists](https://user-images.githubusercontent.com/57936972/76408356-1e69a500-638d-11ea-9069-21f13fac2e75.png)

**Comment by rmakara** [comment]
@akrajna 
Can you create a separate issue for Shopware PWA team based on your research? :)

**Comment by akrajna** [comment]
Issue created #508
