### ISSUE TITLE
Styling of My Account, Use Storefront UI components

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#297]
Use SfTable wherever it might be to style the data grids:

- [x] order history
- [x] addresses
- [x] implement edit forms
- [x] mobile first ;)

**Comment by pspaczek** [comment]
https://storybook.storefrontui.io/?path=/story/pages-my-account--common but, if you can wait to release 0.7.0 than please do it

**Comment by patzick** [comment]
done with #595
