### ISSUE TITLE
As a Team We want to use Postman Collection for Shopware 6 So we operate API faster

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#3]
**Context**
In the VueSF <-> Shopware 6 integration we will use Shopware 6 API a lot. By sharing a Postman Collection, we will be able to save time of team members because they will let them immediately call the endpoints.

**Dependencies**
* No dependencies.

**Acceptance criteria**
* All the endpoints from Shopware6 Sales Channel API are in the collection.
* Domain is configurable.
* IDs are stored as variables in the collection.
* sw-access-key is stored as variable in the collection.
* Collection is shared with other team members.

**Comment by rmakara** [comment]
Postman Collection: https://documenter.getpostman.com/view/1567702/SVtN3rL7?version=latest

Problems found:
* `Context -> Get country states` - Route not found
* `Newsletter -> Confirm newsletter` - Returns 500 error
* `Newsletter -> Update recipient information` - Route not found
* `Customer -> Update email password` - Returns Your password is wrong
* `Customer -> Update password` - Cannot set newPassword parameter
* `Customer -> Update profile information` - SalutationId is blank
* `Cart -> Update line item` - Does not update quantity when quantity is given

**Comment by jensvandorpe** [comment]
@rmakara do you have a postman collection for the latest Shopware 6 version?

**Comment by mkucmus** [comment]
@jensvandorpe you can simply grab one by importing a open api v3 definition which is under /sales-channel-api/v{version}/_info/openapi3.json   endpoint of your SW6 instance :+1: 

here's a super option that postman has 
![Screenshot_20200430_120757](https://user-images.githubusercontent.com/5596960/80699065-af324680-8adb-11ea-94a8-f1974813e066.png)
it accepts openapi3 definitions and some other :muscle: 


but yes, here you have :)
[postman-collection.zip](https://github.com/DivanteLtd/shopware-pwa/files/4557609/postman-collection.zip)
