### ISSUE TITLE
I want to mark existing address as default shipping address So I do not have to choose it every order

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#30]
**Context**
There is a special flag in the addresses, which is Default Shipping Address. I want to be able to set existing address as the default one for the shipping.

**Acceptance Criteria**
* In My Addresses link I can see the possibility of setting an address as default shipping address.
* I can see which address is currently set as default shipping address.
* After I change the default shipping address then I can see the flag at the new default shipping address.
* Default shipping address is used by default in a checkout.

**Comment by mkucmus** [comment]
It was already done.
