### ISSUE TITLE
I want to mark existing address as default billing address So I do not have to choose it every order

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#31]
**Context**
There is a special flag in the addresses, which is Default Billing Address. I want to be able to set existing address as the default one for the billing.

**Acceptance Criteria**
* In My Addresses link I can see the possibility of setting an address as default billing address.
* I can see which address is currently set as default billing address.
* After I change the default billing address then I can see the flag at the new default billing address.
* Default billing address is used by default in a checkout.

**Comment by mkucmus** [comment]
It was already done.
