### ISSUE TITLE
[FEATURE] I want to see Thank you page after placing a dummy order

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#349]
**Describe how this feature will help us improve**

After placing an order, the user is redirected to the Thank you page.
The page contains dummy order details (mocked!!!)

**Is your proposal related to a problem?**
#348 

**Describe the solution you'd considered**

**Acceptance criteria**

- [ ] it looks beautiful on mobile and desktop
- [ ] page has a link to the homepage

**Comment by rmakara** [comment]
@patzick @mkucmus 
There seems to be a duplicate - https://github.com/DivanteLtd/shopware-pwa/issues/23
Can we close #23 ?
