### ISSUE TITLE
[FEATURE] I want to use and display real customer data

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#350]
**Describe how this feature will help us improve**

Being on the checkout page I can see the data taken from the session (context), 
placing an order button invokes the real place-order action (via Shopware API).
Then redirects the user to the thank you page - if success
If an error occurs - show notification with error

**Is your proposal related to a problem?**

#349 #348 

**Acceptance criteria**

- [ ] Addresses are taken from the current's session customer object
- [ ] available shipping and billing methods are fetched from API (using api client)
- [ ] totals are synchronized with backend

**Comment by patzick** [comment]
From #376:

Describe how this feature will help us improve

All the forms should be editable, and such actions should be synchronized with the backend.
For not logged users we better have #375 done before.

Acceptance criteria

 - [ ] validations are plugged into all the editable fields
 - [ ] checkout changes should go through only one service/hook
 - [ ] code is 100% covered by tests

**Comment by patzick** [comment]
we have subtasks for it in: https://github.com/DivanteLtd/shopware-pwa/labels/Checkout
