### ISSUE TITLE
[BUG] After refreshing the page, logged-user token disappears

### ISSUE THREAD

**Issue by krskibin** [DivanteLtd/shopware-pwa#354]
**Describe the bug**

After logging in and refreshing the page, the user token is disappeared from the cookie and the user is logged out.

**How to reproduce**
1. Log in and go to my account
2. Reload the page
3. Instead of my account page, there is login in page

**Expected behavior**
After reloading the page user token should be refreshed and the user should not be logged out.

**Actual behavior**
After reloading the page the user is logged out.

**Devices (please complete the following information):**
- all

**Comment by mkucmus** [comment]
the error does not occur.
checked on both: shopware-pwa and canary version.
