### ISSUE TITLE
I want to choose a shipping method So it may get calculated into the cart totals

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#36]
**Context**
We must be able to select the shipping method in a cart as it may affect the totals of the cart. Each shipping method may have a different value.

**Acceptance Criteria**
* In a Cart Page I can see the possibility to select the shipping methods.
* I can select only the methods available for me according to Shopware logic.
* After I select the shipping method then Shipping Cost and Totals get recalculated.
* Default shipping method is set by default. : )

**Comment by patzick** [comment]
logic exist, but it will not be implemented in default-theme
