### ISSUE TITLE
[FEATURE] add salutation select to the register form

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#363]
**Describe how this feature will help us improve**

Add a possibility of selecting the salutation during the registration progress

**Is your proposal related to a problem?**

![Screenshot_20200205_154446](https://user-images.githubusercontent.com/5596960/73851900-955fcb00-482e-11ea-8def-205eb81aa9c4.png)

**Describe the solution you'd considered**

TODO:

- add appropriate service/method in shopware-api-client package - to get the list of available salutations for current sales channel (GET https://shopware-2.vuestorefront.io/sales-channel-api/v1/salutation)
- add select to the registration form
- use chosen salutationId withing the register request

- consider implementing it on "my account" edit forms.

**Acceptance criteria**

- [ ] the code is 100% covered by tests
- [ ] there is select with available salutations which can be chosen
- [ ] user can be registered with the selected salutation

nice to have: 
- [ ] at least one e2e test is implemented, let's say: only for seeing the select with possible salutations

**Comment by mkucmus** [comment]
related issue: #360

**Comment by akrajna** [comment]
user  Error is not defined in register form
