### ISSUE TITLE
[BUG] Header link to categories list use wrong url (slug generation problem)

### ISSUE THREAD

**Issue by blackgearit** [DivanteLtd/shopware-pwa#365]
**Describe the bug**
When categories in Shopware has complex names (like the one contained into demo data "Free time & Electronics) the header uses wrong slug to request the page data ('free-time \u0026 electronics')

**How to reproduce**
Create a complex Category in Shopware 6 or use demo data

**Expected behavior**
Same slug as one used by Shopware 6

**Actual behavior**
404 page not found from API

**Code examples**
the body of the request to the Shopware 6 API:

```{path: "free-time & electronics/", associations: {options: {associations: {group: {}}}}}```

the response from the api:

```{"errors":[{"code":"0","status":"404","title":"Not Found","detail":"Path `free-time \u0026 electronics\/` could not be resolved."}]}```

**Screenshots**

**Devices (please complete the following information):**
All

NB: with a simpler category name like "clothing", all works.

**Comment by rmakara** [comment]
Thank you for the issue @blackgearit. We will discuss that with the team today. :+1:

**Comment by mkucmus** [comment]
Will be solved with the point 2. from #271. We won't be using the our slugifier, because it's not compatible with logic which shopware does (https://github.com/cocur/slugify).

we can consider using the technical ones in the entire application until the #271 is done
