### ISSUE TITLE
Keeping and getting the guest user data

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#375]
Background:
As the user isn't logged in we need to keep the personal and address data in someplace (perhaps it's in the current session cart). 
The application should have a possibility to distinguish this situation and use the right way to place an order. (commented at useCart/index.ts composable).

TODO:
1. [ ] add methods to save guest user data into the current session
2. [ ] add methods to get guest user data from the current session
3. [ ] handle this case in placeOrder method (temporary stored in useCart)

**Comment by patzick** [comment]
done with internal checkout
