### ISSUE TITLE
[FEATURE] I want to change the customer data on the checkout

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#376]
**Describe how this feature will help us improve**

All the forms should be editable, and such actions should be synchronized with the backend. 
For not logged users we better have #375 done before. 

**Acceptance criteria**

- [ ] validations are plugged into all the editable fields
- [ ] checkout changes should go through only one service/hook
- [ ] code is 100% covered by tests

**Comment by patzick** [comment]
Duplicate of #350
