### ISSUE TITLE
Create Shopware Client package

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#38]
**Context**
After the research we want to build a Shopware Client package and include all the TypeScript interfaces (#41, #42, #43, #44, #45, #46, #47) inside. The purpose of the package is to let all the JS developers work with Shopware API.

**Dependencies**
* Blocked by #37 

**Acceptance criteria**
* Shopware Client package is created up to the standards defined in #37

**Comment by patzick** [comment]
Done with #48
