### ISSUE TITLE
[BUG][Mobile] Side swipe on home page and category page

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#384]
**Describe the bug**
It is possible to side swipe on home page and category page

**How to reproduce**

1. Go to the home page 
2. Swipe from righnt to the left
3. Go to any category page
4. Swipe from right to the left

**Expected behavior**
There should not be possibility to side swipe the page. All components should be visible without horizontal swiping.

**Actual behavior**
It is possible to side swipe the page. Not all components are visible without  horizontal swiping e.g. 'cart' icon in bottom menu

**Screenshots**

![SideSwipe](https://user-images.githubusercontent.com/57936972/74533809-bad98c80-4f32-11ea-91c2-95f2b3b2b654.gif)

**Devices (please complete the following information):**
All mobile devices

**Comment by Michal-Dziedzinski** [comment]
@akrajna can you confirm that it's still exist? :)

**Comment by akrajna** [comment]
@Michal-Dziedzinski the bug does not exist anymore :-)
