### ISSUE TITLE
[BUG] I am unable to init project as described in CHEATSHEET.md

### ISSUE THREAD

**Issue by FlushBG** [DivanteLtd/shopware-pwa#390]
**Describe the bug**
I get an error when trying to initialize a shopware-pwa project using shopware-pwa init. Attempted on Windows 10 64-bit, node version 10.16.3, yarn version 1.19.0

**How to reproduce**
1. Clone repo
2. In project root, execute 'yarn' and 'yarn build --types'
3. Make a new project folder outside of shopware-pwa project root
4. cd inside new project folder
5. Execute 'shopware-pwa init'

**Expected behavior**
A new project to be initialized

**Actual behavior**
Got 'command failed' error (see screenshot) 

**Screenshots**
![image](https://user-images.githubusercontent.com/25154835/74590086-eda78180-5013-11ea-846a-a629c3addab5.png)

**Devices:**
 - Device: Desktop
 - OS: Windows 10 x64
 - Browser: N/A

**Comment by patzick** [comment]
Windows problems with CLI has been fixed, I'm closing this issue.
Here's instruction on how to start: https://github.com/DivanteLtd/shopware-pwa#quick-start

@FlushBG in case of further troubles please let us know :)
