### ISSUE TITLE
[MENU BUTTON][MOBILE] Menu button in bottom bar navigation

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#391]
**Describe how this feature will help us improve**
Navigate through the categories and subcategories on the website on mobile devices

**Describe the solution you'd considered**
after pressing the menu icon the categories list is displayed as below:
<img width="142" alt="MenuButton" src="https://user-images.githubusercontent.com/57936972/74604604-dde57700-50bf-11ea-8da2-deebbe4d10d0.png">

after pressing the category the subcategories are displayed as below:
<img width="147" alt="BottomMenuSubcategories" src="https://user-images.githubusercontent.com/57936972/74604417-108e7000-50be-11ea-9f30-8dc60665fc7c.png">

**Acceptance criteria**

- [ ] after pressing the menu button, list of all categories appears on the screen
- [ ] after pressing one off the categories described above a list of subcategories expands
- [ ] after pressing one of the subcategories user is redirected to the chosen category
- [ ] after pressing the back arrow on the top of the list user is going one step back (at the end the list is closing)
- [ ] after pressing the menu button again, previously opened list of all categories is closed

**Comment by patzick** [comment]
@akrajna can you recheck it and close or put `bug` label?

**Comment by akrajna** [comment]
works fine
