### ISSUE TITLE
[FEATURE] Filters- make sticky buttons 'Done' and 'Clear all' on mobile and desktop

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#397]
**Describe how this feature will help us improve**
Better user experience. It will not be necessary to scroll all the way down to click 'Done' or 'Clear all' button

**Describe the solution you'd considered**
On categories and subcategories pages after clicking the filter a list of  available filters appears with buttons 'Done' and 'Clear all' at the very bottom of it. Make the ' Done'  and 'Clear all' buttons sticky to the bottom of the screen so that they are always visible.
<img width="305" alt="stickyFilterButtons" src="https://user-images.githubusercontent.com/57936972/74641547-c6ff5d00-5171-11ea-97d1-1848705908e4.png">

**Acceptance criteria**

- [ ]  the buttons 'Done' and 'Clear all' are sticked to the bottom of the view so that they are always visible

**Comment by patzick** [comment]
done with #595
