### ISSUE TITLE
[FEATURE]Home page - add carousel 'popular categories'  on mobile

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#401]
**Describe the solution you'd considered**
Add carousel 'popular categories' under main categories buttons - #399 in home page on mobile as below:
<img width="144" alt="HomePageCarousel" src="https://user-images.githubusercontent.com/57936972/74655630-f7082980-518c-11ea-92ae-a712ba235512.png">

**Acceptance criteria**

- [ ]  the carousel with 'popular categories' is added to the home page on mobile
- [ ] user is able to swipe the carousel
- [ ] when user swipes to the last category in the carousel he can swipe back to the left

**Comment by patzick** [comment]
it can be done by CMSes, we will not implement it natively
