### ISSUE TITLE
Product listing - two products in one row on mobile

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#404]
Related to the issue #405 

**Describe the solution you'd considered**
On category and subcategory pages make product listing with two products in one row - description of the product is under the picture (default product listing) as below:
<img width="167" alt="TwoProductsInOneRow" src="https://user-images.githubusercontent.com/57936972/74727198-1d879c80-5241-11ea-8ee4-61bb5dadcc4c.png">

**Acceptance criteria**

- [x]  there are two products in one row with description under the picture on product listing on mobile

**Comment by patzick** [comment]
done
