### ISSUE TITLE
[FEATURE]Product listing - one product in one row on mobile

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#405]
Related to the issue #404 

**Describe the solution you'd considered**
On category and subcategory pages make product listing with one product in one row - description of the product is next to the picture (horizontal product listing) as below:
<img width="189" alt="HorizontalListing" src="https://user-images.githubusercontent.com/57936972/74728874-cf27cd00-5243-11ea-9680-e75e9a9b01c5.png">

Make possible for user to switch from default product listing #404  to horizontal product listing.

**Acceptance criteria**

- [ ]  there is one product in one row with description next to the picture on product listing on mobile
- [ ] user can switch from default product listing- #404 to horizontal product listing

**Comment by pspaczek** [comment]
@akrajna can you add Feature issues at Storefront UI?

**Comment by akrajna** [comment]
related link https://github.com/DivanteLtd/storefront-ui/issues/951

**Comment by patzick** [comment]
will be implemented with #202
