### ISSUE TITLE
[FEATURE] Cart -add popup window after clicking 'go to checkout' button

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#408]
**Describe how this feature will help us improve**
user can login or buy as a guest user

**Describe the solution you'd considered**

Add popup window after clicking 'go to checkout' button for not logged in  users. The user can choose: Sign in, Guest user or Cancel as below:
<img width="172" alt="BeforeCheckout" src="https://user-images.githubusercontent.com/57936972/74735967-0f8e4780-5252-11ea-87be-8f396a1a30aa.png">

**Acceptance criteria**

- [ ]  popup window with selection Sign in, Guest user or Cancel appears after clicking 'go to checkout' for not logged in users
- [ ] after selecting 'Sign in' user is able to log in
- [ ] after logging in user is redirected to checkout
- [ ] after selecting 'Guest user' user is redirecting to checkout
- [ ] after selecting 'Cancel' the popup window closes

**Comment by patzick** [comment]
it has been changed in redesigns, won't be implemented
