### ISSUE TITLE
[BUG] Path `` could not be resolved 404 error from shopware

### ISSUE THREAD

**Issue by blackgearit** [DivanteLtd/shopware-pwa#409]
**Describe the bug**
When I try to visit a path in shopware-pwa, an error "maximum call stack exceeded" is raised on browser and an error  `ERROR  Problem with fetching CMS data:  Request failed with status code 404` is raised on console.

**How to reproduce**
Install Shopware with demo data, install and setup shopware-pwa accordingly with docs, launch shopware pwa with `yarn dev` and visit the provided url

**Expected behavior**
Showing homepage or any other url

**Actual behavior**
A call to `/sales-channel-api/v1/vsf/page` is made by shopware-pwa at page visit with this request body

```
{ path: '',                                                                                             
  associations:
   { options: { associations: { group: { associations: undefined } } } } }```
```
the dumped error data raised from shopware is 

```
{ errors:                                                                                                                                 09:54:46
   [ { code: '0',
       status: '404',
       title: 'Not Found',
       detail: 'Path `` could not be resolved.' } ] }
```

I'm able to get into the pwa homepage by add a dd in shopware source code
`src/VueStorefront/PageLoader/Context/PageLoaderContextBuilder.php`

```
    public function build(Request $request, SalesChannelContext $context): PageLoaderContext
    {
        dd($request);
```
to avoid the exception throw from shopware.
With this hack, I'm able to visit the PWA homepage with the upper Categories Links bar.
If I click on one of these Categories, I get a 500 error code from PWA. Then, remove the `dd` from shopware source code and refresh the page on PWA, I can see the article list.
If I try to visit the PWA homepage again, the "maximum call stack exceeded" error is raised in browser and the `ERROR  Problem with fetching CMS data:  Request failed with status code 404` is raised in console.

**Screenshots**

Homepage visit:

![image](https://user-images.githubusercontent.com/8858847/74820118-baaa0a00-5301-11ea-9d01-5dcf1c4e8ebe.png)

shopware dd hack:

![image](https://user-images.githubusercontent.com/8858847/74820313-18d6ed00-5302-11ea-90ee-4a7cb12f7c28.png)

Homepage visit after shopware dd hack:
![image](https://user-images.githubusercontent.com/8858847/74820152-d1e8f780-5301-11ea-8cd8-aad2a42ce6b1.png)

**Devices (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all

**Comment by patzick** [comment]
hey @blackgearit , is this problem fixes with the newest version?

**Comment by blackgearit** [comment]
Will ask to my colleague @CthulhuDev

**Comment by CthulhuDev** [comment]
Issue can be closed, the problem cannot be reproduced with the latest versions
