### ISSUE TITLE
[FEATURE]404 Page on mobile

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#410]
**Describe how this feature will help us improve**
Make the 404 looks good

**Describe the solution you'd considered**
Make the 404 page on mobile as below:
<img width="177" alt="404Page" src="https://user-images.githubusercontent.com/57936972/74838918-b216fb00-5324-11ea-8614-8cd37526cdce.png">

**Acceptance criteria**

- [ ]  the 404 page looks like on the picture above
- [ ] after pressing the 'return to home' button the user is redirected to homepage

**Comment by patzick** [comment]
done with #595
