### ISSUE TITLE
[FEATURE]500 page on mobile

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#411]
**Describe how this feature will help us improve**
Make the 500 error page looks good

**Describe the solution you'd considered**
Make the 500 error page on mobile as below:
<img width="142" alt="500ErrorPage" src="https://user-images.githubusercontent.com/57936972/74842156-3455ee00-532a-11ea-968c-b923da774d85.png">

**Acceptance criteria**

- [ ]  the 500 page looks like on the picture above
- [ ] after pressing the 'return to home' button the user is redirected to homepage

**Comment by patzick** [comment]
done

**Comment by patzick** [comment]
#595
