### ISSUE TITLE
[BUG]My account - Email change is not working

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#416]
**Describe the bug**
In my account the option Email change is not working. 

**How to reproduce**
Initial condition: user is logedin
1. Go to 'My account'
2. Click on 'Email change'
3. Fill in the fields: 'Your new e-mail', 'Confirm e-mail', 'Your password'
4. Click on 'UPDATE EMAIL'
-->

**Expected behavior**
User is able to change his email address in My account

**Actual behavior**
User is not able to change his email address in My account

**Screenshots**
<img width="809" alt="EmailChange" src="https://user-images.githubusercontent.com/57936972/74933544-80fdff80-53e4-11ea-823d-771c2407b2f9.png">

**Devices (please complete the following information):**
All devices

**Comment by Michal-Dziedzinski** [comment]
related to #555 and will be closed there as well

**Comment by patzick** [comment]
done, @akrajna please reopen if the problem still occurs

**Comment by akrajna** [comment]
The bug still exists. It is impossible to change email in My account.

**Comment by akrajna** [comment]
It works correctly
