### ISSUE TITLE
[BUG]Checkout- the page 'Personal details' is filled in with one user data

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#418]
**Describe the bug**
Checkout- the page Personal details is filled in with one user data. It is always the same user - 'John Doe'. It is happening for logged in and not logged in users.

**How to reproduce**

First scenario: 
Not logged in user
1. Go to any product page
2. Add that product to the cart
3. Go to the cart
4. Click 'Go to checkout' button
5. See the error

Second scenario: 
Repeat the steps from 1 to 5 for logged in user

**Expected behavior**
For not logged in user- after clicking the 'Go to checkout' button, the page 'Personal details' should have all the input fields empty

For logged in user- after clicking the 'Go to checkout' button, the page 'Personal details' should be field in with data of the user who is logged in

**Actual behavior**
After clicking the 'Go to checkout' button, the page 'Personal details' is filled in with one user data.

**Screenshots**
![CheckoutJohnDoe](https://user-images.githubusercontent.com/57936972/74939569-6c276900-53f0-11ea-85ba-1c2cd083af73.gif)

**Devices (please complete the following information):**
All devices

**Comment by patzick** [comment]
done with internal checkout
