### ISSUE TITLE
[BUG]CMS componenets  -wrong size of the picture from 'Hero image' block

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#423]
**Describe the bug**
CMS components  -the size of the picture inserted into the block named 'Hero image' from block category 'Text&images' is not the same on the page as it is in Shopware 'Shopping Experiences' layout

**How to reproduce**
1. Go to 'Shopping experiences' from Shopware
2. Choose layout called 'Test Shop page'
3. Click 'Settings' icon
4. Click 'block' icon
5. Select block category 'Text&images'
6. Add 'Hero image' to the Layout
7. Upload background image
8. Click 'Save'
9. Go to 'Categories' from Shopware
10. Go to 'Clothing' - 'Movies & Toys'
11. Click on 'Category active' button in order to make it active
12. Click 'Save' button
13. Check how does it look on https://shopware-pwa-faint-money.now.sh/

**Expected behavior**
Pictures placed in the block 'Hero image' should have the same size and look the same in Shopware 'Shopping Experiences' layout as on the website

**Actual behavior**
Pictures look different in Shopware 'Shopping Experiences' layout and on the website 

**Screenshots**
The picture in Shopware 'Shopping Experiences' layout looks like this:
<img width="880" alt="ShopwareExperienceLayout" src="https://user-images.githubusercontent.com/57936972/75022823-0c37cd80-5497-11ea-92d3-8ede93f91578.png">

The same picture on the website looks like this:
<img width="661" alt="Shopware-pwa" src="https://user-images.githubusercontent.com/57936972/75022816-093cdd00-5497-11ea-8b41-e7f84b41e066.png">

**Devices (please complete the following information):**
All devices

**Comment by patzick** [comment]
done with CMS restructure
