### ISSUE TITLE
[BUG] CMS components - block  'Three columns, boxed images & text' is not displayed correctly on the website

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#425]
**Describe the bug**
CMS components - block  'Three columns, boxed images & text' is not displayed correctly on the website. There should be three columns: image, text, image

**How to reproduce**

Initial condition: the subcategory 'Movies & Toys' is set to active in Shopware 
1. Go to 'categories' from Shopware
2.  Select 'Clothing'-'Movies & Toys' from category structure
3. Go to 'Layout assignment'
4. Click 'Edit in designer' button
5. Check if there is block  'Three columns, boxed images & text', if not add one
6. Go to subcategory 'Movies & Toys' on our website
7. See the error

**Expected behavior**
Block  'Three columns, boxed images & text' is displayed correctly on the website. There should be three columns: image, text, image.

**Actual behavior**
Block  'Three columns, boxed images & text' is not displayed correctly on the website. The pictures are one under another ant there is no text at all.

**Screenshots**
Block 'Three columns, boxed images & text' in Shopware 'Shopping Experiences' layout:
<img width="651" alt="3columnsBlockShopware" src="https://user-images.githubusercontent.com/57936972/75036878-2da6b280-54b3-11ea-9b8e-c36721b00e13.png">

Page on our website with the 'Three columns, boxed images & text' block:
<img width="238" alt="3columnsBlockWeb" src="https://user-images.githubusercontent.com/57936972/75036892-35665700-54b3-11ea-952f-898f70e1b0df.png">

**Devices (please complete the following information):**
All devices

**Comment by Michal-Dziedzinski** [comment]
Moved to #426
