### ISSUE TITLE
[BUG]CMS components - Block 'Images' - the pictures are not shown in the right places

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#426]
**Describe the bug**
Block category 'Images' - the pictures are not shown in the right places. Doesn't matter if you choose 'Three columns, rounded' block or 'Image grid' block the pictures are shown one after another, not  rounded and not in grid

**How to reproduce**

1. Go to 'categories' from Shopware
2. Select 'Clothing'-'Movies & Toys' from category structure
3. Go to 'Layout assignment'
4. Click 'Edit in designer' button
5. Click 'Settings' icon
5. Click 'block' icon
6. Select block category 'Images'
7. Add 'Two columns, boxed', 'Three columns, boxed', 'Three columns, full-sized',' Four columns, boxed', 'Three columns, rounded', 'Three columns, boxed & background', 'Image grid'
8. Hover on each image, click 'setting' icon and upload picture 
9. Click 'Save' button in the upper right corner
10. Go to subcategory 'Movies & Toys' on our website
11. See the error

**Expected behavior**
Pictures should be displayed in the right places and shapes and look the same as in Shopware layout.

**Actual behavior**
Pictures are displayed in wrong places and shapes on the website.

**Screenshots**
'Three columns, rounded' block in Shopware 'Shopping Experiences' layout:
<img width="907" alt="3columRoundedShopware" src="https://user-images.githubusercontent.com/57936972/75038858-98f28380-54b7-11ea-825c-2084131fbeaf.png">

'Three columns, rounded' block on the website looks like this:
<img width="195" alt="3columnRoundedWeb" src="https://user-images.githubusercontent.com/57936972/75038870-a4de4580-54b7-11ea-94d5-eed226440770.png">

**Devices (please complete the following information):**
All devices

**Comment by akrajna** [comment]
'Three columns, rounded' block works correctly. 
For the other blocs ( 'Two columns, boxed', 'Three columns, boxed', 'Three columns, full-sized',' Four columns, boxed', 'Three columns, boxed & background', 'Image grid') new issues will be created.

**Comment by Michal-Dziedzinski** [comment]
However, we return to the idea of a joint issue to avoid conflicts with pull requests. The idea of creating components has changed after plugins workshop (separete components for every block)

**Comment by rmakara** [comment]
Blocked by #234

**Comment by rmakara** [comment]
PR for this issue must be adjusted up to the new requirements after merging #234
