### ISSUE TITLE
I want to see the breadcrumbs and use it for navigation

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#428]
**Context**
When I enter Product Page from specific page within our eCommerce store then I want to see the breadcrumbs. Also when I receive a link to the product from my friend then I want to see the breadcrumbs.

**Acceptance Criteria**
* I can see breadcrumbs on the product page.
* I can click breadcrumb links to navigate to other pages.
* Breadcrumbs are correct (consider product in 1 category, product in many categories, getting link to product page from a friend).

**Comment by rmakara** [comment]
@patzick

**Comment by patzick** [comment]
this is done :)
