### ISSUE TITLE
[BUG]CMS component - sidebar blocks are on the wrong side to each other

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#430]
**Describe the bug**
If you choose a page layout containing a sidebar the block putted in left column sometimes is shown on the right side on the website

**How to reproduce**
Initial conditions: the category 'Movies & Toys' is active

1. Go to 'Shopping experiences' from Shopware
2. Choose layout called 'Test Shop page'
3. Scroll down and click 'add-section' button
4. Click 'Sidebar'
5. Click 'Settings' icon
6. Add any block to the left section and any different block to the right section
7. Click 'Save' button in the upper right corner
8. Click 'Navigator' button on the right side 
9. Go to Layout section - Sidebar
10. Click 'delete' button next to each block you just added
11. Click 'Save' button in the upper right corner
11. Add again any block to the left section and any different block to the right section
12. Click 'Save' button in the upper right corner
13. Got to the website and See the error
14. If the components are on the right place repeat steps 10-13 until you see the error

**Expected behavior**
Block putted in left column is always shown on the left side on the website and block putted in the right column is always shown on the right side. The sidebar blocks are on the correct side.

**Actual behavior**
Sometimes sidebar blocks are putted on the wrong side to each other on the website.

**Screenshots**
Sidebar blocks in Shopware 'Shopping Experiences' layout:

<img width="913" alt="SidebarsShopwareShoppingExperience" src="https://user-images.githubusercontent.com/57936972/75137665-7c895d80-56e8-11ea-8cdf-44fb03f7791a.png">

The same sidebar blocks on the website:
<img width="807" alt="SidebarWebsite" src="https://user-images.githubusercontent.com/57936972/75137703-92971e00-56e8-11ea-9f25-966b10af3ae0.png">

**Devices (please complete the following information):**
All devices

**Comment by patzick** [comment]
@Michal-Dziedzinski please check it

**Comment by akrajna** [comment]
It is already working correctly.
