### ISSUE TITLE
[BUG]CMS Components- block 'Navigation' is not working

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#431]
**Describe the bug**
Block category 'Navigation' is not working. After placing 'Navigation' on layout in Shopware Experience it does not appear correctly on website. Instead of whole category tree there is written: 'Subcategories
No subcategories'

**How to reproduce**

1. Initial conditions: the category 'Movies & Toys' is active

1. Go to 'Shopping experiences' from Shopware
2. Choose layout called 'Test Shop page'
3. Click 'Settings' icon
4. Click 'block' icon
5. Select block category 'Sidebar'
6. Add 'Navigation' to the Layout
7. Click 'Save' button in the upper right corner
8. Go to subcategory 'Movies & Toys' on our website
9. See error

**Expected behavior**
After adding the 'Navigation' block to the layout, the entire category tree is visible on the page. All categories are selectable.

**Actual behavior**
After adding the 'Navigation' block to the layout, the category tree is not visible on the page.

**Screenshots**
'Navigation' block in Shopware 'Shopping Experiences' layout:
<img width="950" alt="NavigationShopware" src="https://user-images.githubusercontent.com/57936972/75146708-ecedaa00-56fb-11ea-962c-9361d8cf315b.png">

'Navigation' block on the website:
<img width="810" alt="NavigationWebsite" src="https://user-images.githubusercontent.com/57936972/75146719-f1b25e00-56fb-11ea-900c-eefafb9ef6ce.png">

**Devices (please complete the following information):**
All devices

**Comment by patzick** [comment]
@akrajna can you recheck it?

**Comment by akrajna** [comment]
It is not working correctly. There is the navigation block on the side but after clicking on the subcategory the 404 error page appears.

**How to reproduce**

Steps to reproduce the behavior:
1. Go to the category 'Accessories'
2. Click on the subcategory 'Movies' 'See Movies' form the side menu
3. See the error
4. Click on subcategory 'Movies' from the MegaMenu

* subcategory 'Movies' 'See Movies' form the side menu
<img width="798" alt="Accesiories" src="https://user-images.githubusercontent.com/57936972/82789200-361fd800-9e6a-11ea-875f-2de25255388b.png">
* subcategory 'Movies' from the MegaMenu
<img width="843" alt="Accesories1" src="https://user-images.githubusercontent.com/57936972/82789231-40da6d00-9e6a-11ea-95a9-ac24efc1e86e.png">

**Comment by akrajna** [comment]
it is working correctly
