### ISSUE TITLE
[BUG]CMS Components - the link added to the 'Images' block does not work

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#432]
**Describe the bug**
The link added to the 'Images' block does not work on website.

**How to reproduce**

Initial conditions: the category 'Movies & Toys' is active

1. Go to 'Shopping experiences' from Shopware
2. Choose layout called 'Test Shop page'
3. Click 'Settings' icon
4. Click 'block' icon
5. Select block category 'Images'
6. Add any image block to the Layout
7. Click on the 'Element settings' icon on the added block 
8. Add any picture
9. Put any link in the 'Link to' field
10. Click 'Done' button
11. Click 'Save' button in the upper right corner
12. Go to subcategory 'Movies & Toys' on our website
13. Click on the added picture and see error

**Expected behavior**
The link added to the 'Images' block works on website.  After clicking on the picture with the added link the user is redirected to the appropriate website.

**Actual behavior**
The link added to the 'Images' block does not work on the website.  After clicking on the picture with the added link nothing happens. 

**Screenshots**
Link added to the image in Shopware Shopping Experience:
<img width="945" alt="LinkPictureShopware" src="https://user-images.githubusercontent.com/57936972/75148406-da756f80-56ff-11ea-9cdb-9da0b37e319f.png">

The same image on the website:
<img width="902" alt="LinkPictureWebsite" src="https://user-images.githubusercontent.com/57936972/75148407-de08f680-56ff-11ea-9c25-6c3fc29e3552.png">

**Devices (please complete the following information):**
All devices

**Comment by patzick** [comment]
## What needs to be done
- only CmsElementImage.vue needs to be changed at first
- some additional logic with URLs may be moved then to helpers but after consultations
- all information will be found in `content` which is already passed to the component as a prop

## Acceptance criteria
- [ ] click works internally with `nuxt-link` component
- [ ] external links are used, than <a> should be used
- [ ] open tab/not open tab should be concidered
- [ ] no link component if CMS content doesn't have it

**Comment by akrajna** [comment]
rechecked, it is still an issue
