### ISSUE TITLE
[BUG]CMS Components- products in 'Commerce' block are are not shown in the right places

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#433]
**Describe the bug**
Block category 'Commerce' - the products are not shown in the right places. Products in 'Three columns, product boxes' block are shown one after another, not one next to another.

**How to reproduce**

Initial conditions: the category 'Movies & Toys' is active

1. Go to 'categories' from Shopware
2. Select 'Clothing'-'Movies & Toys' from category structure
3. Go to 'Layout assignment'
4. Click 'Edit in designer' button
5. Click 'Settings' icon
6. Click 'block' icon
7. Select block category 'Commerce'
8. Add 'Three columns, product boxes'
9. Click 'setting' icon and add products on each product boxes
10. Click 'Save' button in the upper right corner
11. Go to subcategory 'Movies & Toys' on our website
12. See error

**Expected behavior**
Products in 'Three columns, product boxes' block are shown one next to another on the website.

**Actual behavior**
Products in 'Three columns, product boxes' block are shown one under another on the website.

**Screenshots**
'Three columns, product boxes' block in Shopware 'Shopping Experiences' layout:
<img width="951" alt="3columnProductShopware" src="https://user-images.githubusercontent.com/57936972/75153930-d9970a80-570c-11ea-840d-1d7a148bf030.png">

'Three columns, product boxes' on the website:

<img width="300" alt="3ColumnProductWebsite" src="https://user-images.githubusercontent.com/57936972/75153937-dbf96480-570c-11ea-81a5-7ada4660568d.png">

**Devices (please complete the following information):**
All devices

**Comment by patzick** [comment]
@akrajna can you rechek it?

**Comment by akrajna** [comment]
I have rechecked it and it seems the 'Three columns, product boxes' block is not implemented. Because there is the information: 'Block product-three-column is not implemented yet!' on the page.
<img width="455" alt="ThreeColumnBlockNotImplemented" src="https://user-images.githubusercontent.com/57936972/85842625-4c3df280-b7a0-11ea-9afe-87bfd6886342.png">

**Comment by akrajna** [comment]
A new issue for it is created #897
