### ISSUE TITLE
[BUG] My account - in My addresses edit address does not work

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#439]
**Describe the bug**
In 'My account' in the tab 'My addresses' the function 'Edit' address is not working properly. Instead of editing an existing address, a new address is created and added to the address list.

**How to reproduce**
Initial condition: user is logged in

1. Go to 'My addresses' in 'My account'
2. Click on the 'arrow' icon next to one address on the list
3. Fill in all the required fields
4. Click on 'Update the address' button

**Expected behavior**
The existing address is changed after clicking on 'Update the address' button.

**Actual behavior**
The existing address is not changed after clicking on 'Update the address' button instead a new address is created.

**Screenshots**
![MyAccountEditAddress](https://user-images.githubusercontent.com/57936972/75248234-1417aa80-57d4-11ea-9fc3-1b44839671b7.gif)

**Devices (please complete the following information):**
All devices

**Comment by rmakara** [comment]
There was an original issue for that. Copying ACs here and closing the duplicate. 

CC: @krskibin  @akrajna  @Michal-Dziedzinski 

https://github.com/DivanteLtd/shopware-pwa/issues/29

**Acceptance Criteria**
* I can access the list of My Addresses.
* I can see the button for editing the existing addresses.
* I can see the form with: salutation, country, first name, last name, street, zipcode, city.
* When I save the address with all the correct data in a form then updated address data is visible in the address list.
* When I open that address form once again then I see updated address data.
* When I try to save the address without required data in a form then I see validation error message.
* I can use that updated address in the cart/checkout later.
