### ISSUE TITLE
[BUG] XSS vulnerability in My account - change/add address

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#440]
**Describe the bug**
In 'My account' in the tab 'My addresses' in add address form it is possible put html code, which is executed after clicking 'Update the address code'

**How to reproduce**
Initial condition: user is logged in

1. Go to 'My addresses' in 'My account'
2. Click on the 'arrow' icon next to one address on the list
3. Fill in all the required fields
5. Write in one field html code e.g. <img width="91" alt="xsseg" src="https://user-images.githubusercontent.com/57936972/75325693-8a221d00-5879-11ea-9ef3-f0f866c04fd5.png">

4. Click on 'Update the address' button
5. See error

**Expected behavior**
After filling in the form with any html code it is not executed. 

**Actual behavior**
After filling in the form with any html code it is executed.

**Screenshots**
![XSS](https://user-images.githubusercontent.com/57936972/75325277-d6209200-5878-11ea-852e-101d74cfc649.gif)

**Devices (please complete the following information):**
All devices

**Comment by krskibin** [comment]
Hi, I figure it out that Shopware backend sanitizes all strings that we sent in API requests and returns its escaped versions, so XSS attack is not possible.
