### ISSUE TITLE
[BUG] Category page - information on a product list without products should be centered

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#445]
**Describe the bug**
The information 'No products found let us look for them' on a product list without products is on the left side of the page on desktop and mobile

**How to reproduce**

1. Go to any category with no products e.g. Clothing - Jewelry
2. See error

**Expected behavior**
The information 'No products found let us look for them' is in the center of the page

**Actual behavior**
The information 'No products found let us look for them' is on the left side of the page on desktop and mobile

**Screenshots**
<img width="695" alt="NoProductsOnCategory" src="https://user-images.githubusercontent.com/57936972/75336655-cfe7e100-588b-11ea-9a4b-693ecc8b531c.png">

**Devices (please complete the following information):**
All devices

**Comment by ahmed-adly-ali** [comment]
has this been fixed?

**Comment by patzick** [comment]
@ahmed-adly-ali yes, isn't it working for you?

**Comment by ahmed-adly-ali** [comment]
it's working now. Thanks, Patzick
