### ISSUE TITLE
[BUG] Cannot develop project on Windows

### ISSUE THREAD

**Issue by krskibin** [DivanteLtd/shopware-pwa#446]
**Describe the bug**
On Windows project cannot be build due to the platform incompabilites. For instance, you cannot run shopware-pwa cli, because of the incorrect file format or you cannot build the developer version due to the problem with vuex store instance.

**Expected behavior**
Developers should be able to be developed the project on Windows systems

**Actual behavior**
Cannot develop project on Windows

**Screenshots**

**Devices (please complete the following information):**
 - OS: all Windows devices

**Comment by patzick** [comment]
done with #663
