### ISSUE TITLE
[BUG] components do not compile; Undefined variable: "$spacer".

### ISSUE THREAD

**Issue by alexSanni** [DivanteLtd/shopware-pwa#448]
**Describe the bug**
Default components don't compile when i start yarn build process because @storefront-ui/vue has strongly changed.

**How to reproduce**
initialize a fresh project with `shopware-pwa init`. `yarn dev` will fail

**Expected behavior**
green build

**Actual behavior**
red build

**Screenshots**
<img width="1920" alt="Bildschirmfoto 2020-02-26 um 12 40 06" src="https://user-images.githubusercontent.com/1966644/75341657-2dccf680-5895-11ea-9cca-505161e29fb7.png">

**Comment by alexSanni** [comment]
in package.json change
`"@storefront-ui/vue": "latest",`
to
`"@storefront-ui/vue": "^0.5.1",`
and execute yarn install

**Comment by krskibin** [comment]
We've been working at the migration to the newest Storefront-UI version, here is the PR #442
