### ISSUE TITLE
[BUG] Misplaced props for SfPrice

### ISSUE THREAD

**Issue by aniamusial** [DivanteLtd/shopware-pwa#450]
**Describe the bug**

**How to reproduce**

1. Go to Category view and see the order of regular price and the discount
2. Click on product card with the discout
3. See the error - regular price and discount are misplaced

**Expected behavior**
Price is the same on Category view and Product details

**Screenshots**

![Screenshot from 2020-02-27 12-26-38](https://user-images.githubusercontent.com/41487496/75440653-74d1ef00-595c-11ea-92eb-a5aea71f9cca.png)
![Screenshot from 2020-02-27 12-26-27](https://user-images.githubusercontent.com/41487496/75440669-7ac7d000-595c-11ea-9957-642636973e9a.png)

**Comment by patzick** [comment]
done with #595
