### ISSUE TITLE
[BUG]My account- edit/add addresses drop down fields does not work on mobile

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#454]
**Describe the bug**
Drop down fields does not work on mobile in my account - My addresses edit/ add address and in My account - My profile 

**How to reproduce**
Initial condition: user is logged in
1. Go to 'My account'
2. Click on 'My addresses'
3. Click on edit address icon
4. Click on 'Salutation' and on 'Country'
5. See the error
6. Go to 'My profile' in my account
7. Try to change Salutation

**Expected behavior**
Drop down fields  work properly on mobile in my account

**Actual behavior**
Drop down fields does not work on mobile in my account as below:

![DropDownMyaccountMobile](https://user-images.githubusercontent.com/57936972/75680714-75d38b00-5c92-11ea-8bcf-232427277c7e.gif)

**Devices (please complete the following information):**
Mobile

**Comment by patzick** [comment]
done with #595
