### ISSUE TITLE
[BUG]Product Page - after opening the bottom of this page is displayed 

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#483]
**Describe the bug**
Sometimes after opening  product page the bottom of it is displayed instead of the top with the product description and pictures.

**How to reproduce**

1. Go to 'Home page'
2.  Scroll down to the bottom of the page
3. Click on any product

**Expected behavior**
After opening  product page always the top of it is displayed with the product description and pictures.

**Actual behavior**
When user scrolls down and than is opening any product page the bottom of the page is displayed and user needs to scroll up in order to see the product description and pictures. The same happened when user is clicking on one of the product from the section 'You may also like' on product page.

**Screenshots**
![ProductPageOpenBottom](https://user-images.githubusercontent.com/57936972/76406319-d2693100-6389-11ea-95ac-1587052a036e.gif)

![ProductPageOpenBottom1](https://user-images.githubusercontent.com/57936972/76406543-2ecc5080-638a-11ea-81e3-2228f17572a7.gif)

**Devices (please complete the following information):**
 All devices

**Comment by patzick** [comment]
it's probably vue router setting, needs to be checked

**Comment by patzick** [comment]
https://nuxtjs.org/api/configuration-router/#scrollbehavior 

the default behaviour should be overridden.
- [ ] category to the product should scroll to top
- [ ] going back should scroll down to a place where we clicked the product
