### ISSUE TITLE
[BUG]Categories, logo and bottom bar navigation are not displayed on  iOS, v9 and less

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#489]
**Describe the bug**
Categories, logo and bottom bar navigation are not displayed on  iOS, v9 

**How to reproduce**

1. Go to Home page on iOS v9 or less
2. See the error

**Expected behavior**
Categories, logo and bottom bar navigation are correctly displayed on  iOS, v9 - v7

**Actual behavior**
Categories, logo and bottom bar navigation are not displayed on  iOS, v9 and less

**Screenshots**
![iOSv9](https://user-images.githubusercontent.com/57936972/76546009-09733b80-648b-11ea-8284-8790893a24f1.png)

**Devices (please complete the following information):**
iOS v9 and less

**Comment by patzick** [comment]
@akrajna can you recheck? Potentially fixed with #595

**Comment by akrajna** [comment]
is included in this issue #780
