### ISSUE TITLE
[BUG]404 error page on Subcategories 

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#490]
**Describe the bug**
There is 404 error page on 'Accessories' Subcategories

**How to reproduce**

1. Go to 'Accessories' category page
2. Click on any subcategory
3. See the error

**Expected behavior**
After clicking on any subcategory the corresponding page is opened

**Actual behavior**
After clicking on any subcategory from the category 'Accessories' the 404 error page is displayed

**Screenshots**
![404Accessories](https://user-images.githubusercontent.com/57936972/76547073-e184d780-648c-11ea-825c-166699f82637.png)

**Devices (please complete the following information):**
All devices

**Comment by patzick** [comment]
it should be fixed on shopware admin site
