### ISSUE TITLE
[Checkout] Go to checkout button always visible on cart

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#504]
Go to checkout button hides when there are multiple products

![image](https://user-images.githubusercontent.com/13100280/76885816-21c6ca00-6880-11ea-9b87-562184312d7b.png)

## Acceptance criteria
- [ ] button and totals are always visible no matter how many products if there
- [ ] same in mobile
- [ ] if there are no products in cart "Start shopping" button closes cart

**Comment by pspaczek** [comment]
https://github.com/DivanteLtd/storefront-ui/pull/888 at Storefront UI 0.7.0 you can find sticky content #bottom

**Comment by patzick** [comment]
done with #595
