### ISSUE TITLE
[Checkout][Review] I want to change items quantity on review

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#505]
## Acceptance criteria
- [x] I can change items quantity in the review step
- [x] On mobile I can see order items in the review step and change their quantity

**Comment by akrajna** [comment]
It is possible to change the items quantity to be negative integer or 0 or leave the field empty.
![ChangeQtyinReview](https://user-images.githubusercontent.com/57936972/77147730-3a0c3400-6a8e-11ea-8202-3f18cfbcd891.gif)

Quantity field should accept only integers > 0

**Comment by mkucmus** [comment]
I think it's UI stuff, @patzick WDYT?

**Comment by akrajna** [comment]
It will be done in this issue https://github.com/DivanteLtd/storefront-ui/issues/932
