### ISSUE TITLE
[BUG]CMS components -'Two columns, boxed' the pictures are not shown in the right places

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#509]
**Describe the bug**
Block category 'Images' - 'Two columns, boxed' the pictures are shown one after another instead of in two columns.

**How to reproduce**

1. Go to 'categories' from Shopware
2. Select 'Clothing'-'Movies & Toys' from category structure
3. Go to 'Layout assignment'
4. Click 'Edit in designer' button
5. Click 'Settings' icon
5. Click 'block' icon
6. Select block category 'Images'
7. Add 'Two columns, boxed'
9. Click 'Save' button in the upper right corner
10. Go to subcategory 'Movies & Toys' on our website
11. See the error

**Expected behavior**
Pictures should be displayed in two columns and look the same as in Shopware layout.

**Actual behavior**
Pictures are displayed one after another (in two rows) on the website.

**Screenshots**
'Two columns, boxed' block in Shopware 'Shopping Experiences' layout:
<img width="634" alt="2columnsShopware" src="https://user-images.githubusercontent.com/57936972/76959458-eaa4f700-6919-11ea-9bb2-e09b0b811e70.png">

'Two columns, boxed' block on the website looks like this:
<img width="233" alt="2columnsPWA" src="https://user-images.githubusercontent.com/57936972/76959468-ee387e00-6919-11ea-9dd1-1fef175d63ce.png">

**Devices (please complete the following information):**
All devices

**Comment by Michal-Dziedzinski** [comment]
Moved to #426
