### ISSUE TITLE
[BUG]CMS components -'Three columns, boxed' the pictures are not shown in the right places

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#513]
**Describe the bug**
Block category 'Images' - 'Three columns, boxed' the pictures are shown one after another instead of in three columns.

**How to reproduce**
1. Go to 'categories' from Shopware
2. Select 'Clothing'-'Movies & Toys' from category structure
3. Go to 'Layout assignment'
4. Click 'Edit in designer' button
5. Click 'Settings' icon
5. Click 'block' icon
6. Select block category 'Images'
7. Add 'Three columns, boxed'
9. Click 'Save' button in the upper right corner
10. Go to subcategory 'Movies & Toys' on our website
11. See the error

**Expected behavior**
Pictures should be displayed in three columns and look the same as in Shopware layout.

**Actual behavior**
Pictures are displayed in wrong places - one under another.

**Screenshots**
'Three columns, boxed' block in Shopware 'Shopping Experiences' layout:
<img width="641" alt="3kolumnsShopware" src="https://user-images.githubusercontent.com/57936972/77046277-f00a4c00-69c2-11ea-998a-0c6ae1d2e127.png">

'Three columns, boxed' block on the website looks like this:
<img width="252" alt="3kolumnsPWA" src="https://user-images.githubusercontent.com/57936972/77046201-ce10c980-69c2-11ea-8fdd-4451792b390a.png">

**Devices (please complete the following information):**
All devices

**Comment by Michal-Dziedzinski** [comment]
It is related to #509 and it will be resolved there
