### ISSUE TITLE
[BUG]CMS components -' Four columns, boxed' the pictures are not shown in the right places

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#515]
**Describe the bug**
Block category 'Images' -' Four columns, boxed'' the pictures are shown one after another instead of in four columns.

**How to reproduce**

1. Go to 'categories' from Shopware
2. Select 'Clothing'-'Movies & Toys' from category structure
3. Go to 'Layout assignment'
4. Click 'Edit in designer' button
5. Click 'Settings' icon
5. Click 'block' icon
6. Select block category 'Images'
7. Add ' Four columns, boxed'
9. Click 'Save' button in the upper right corner
10. Go to subcategory 'Movies & Toys' on our website
11. See the error

**Expected behavior**
Pictures should be displayed in four columns and look the same as in Shopware layout.

**Actual behavior**
Pictures are displayed in wrong places - one under another.

**Screenshots**

' Four columns, boxed' block in Shopware 'Shopping Experiences' layout:
<img width="732" alt="4columnShopware" src="https://user-images.githubusercontent.com/57936972/77047655-6445ef00-69c5-11ea-968b-4f805819262a.png">

' Four columns, boxed' block on the website looks like this:
<img width="197" alt="4columnPWA" src="https://user-images.githubusercontent.com/57936972/77047664-68720c80-69c5-11ea-93fa-9ffaf89924ca.png">

**Devices (please complete the following information):**
All devices

**Comment by Michal-Dziedzinski** [comment]
It is related to #509 and it will be resolved there
