### ISSUE TITLE
[BUG]CMS components -'Image grid' the pictures are not shown in the right places

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#517]
**Describe the bug**
Block category 'Images' -'Image grid' the pictures are shown one after another instead of in a grid.

**How to reproduce**

1. Go to 'categories' from Shopware
2. Select 'Clothing'-'Movies & Toys' from category structure
3. Go to 'Layout assignment'
4. Click 'Edit in designer' button
5. Click 'Settings' icon
5. Click 'block' icon
6. Select block category 'Image grid'
7. Add 'Image grid'
9. Click 'Save' button in the upper right corner
10. Go to subcategory 'Movies & Toys' on our website
11. See the error

**Expected behavior**
Pictures should be displayed in a grid and look the same as in Shopware layout.

**Actual behavior**
Pictures are displayed in wrong places - one under another.

**Screenshots**
'Image grid' block in Shopware 'Shopping Experiences' layout:
<img width="690" alt="GridShopware" src="https://user-images.githubusercontent.com/57936972/77051743-14b6f180-69cc-11ea-96c7-e22d465188b2.png">

'Image grid' block on the website looks like this:
<img width="199" alt="GridPwa" src="https://user-images.githubusercontent.com/57936972/77051751-17b1e200-69cc-11ea-9575-a1399780bdf4.png">

**Devices (please complete the following information):**
All devices

**Additional context**

**Comment by Michal-Dziedzinski** [comment]
Moved to #426
