### ISSUE TITLE
[BUG] shared Slack invite link in Readme.md is no longer active

### ISSUE THREAD

**Issue by s-diez** [DivanteLtd/shopware-pwa#539]
**Describe the bug**

The shared Slack invite link in line 39 of the README.md is no longer active.

https://github.com/DivanteLtd/shopware-pwa/blob/c6348b0ee0e7aaded500c57cab2fdaeb19e523e9/README.md#L39

**How to reproduce**

1. Go to the GitHub Page https://github.com/DivanteLtd/shopware-pwa
2. Scroll down to "Join the community on Slack"
3. Click the link labeled "invitation link"
4. See the error page from slack

**Expected behavior**

1. as above
2. as above
3. as above
4. See a form from slack to register for the slack of vuestorefront

**Comment by patzick** [comment]
it has been fixed then, closing issue :)
