### ISSUE TITLE
Documentation 404

### ISSUE THREAD

**Issue by s-diez** [DivanteLtd/shopware-pwa#540]
Hello,

Not really a Bug, but the documentation linked in the README.md https://shopware-pwa-docs.netlify.com/#introduction-to-shopware-pwa just shows a 404 page. This has been for a while, at least 1-2 weeks. Some time back it was working as expected. Is this known? Did the documentation change and is now somewhere else?

We would like to use this application for an upcoming project. Would be nice to have a working documentation to get some further information.

Looking forward to the finished version. :)

Greetings
Sebastian Diez

**Comment by patzick** [comment]
fixed, sorry for that :)
