### ISSUE TITLE
Determine the requests' parameters interfaces

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#55]
**The Criteria interface**
All possible criteria should? be contained in one consistent object and gathers all methods to manipulate the ouput of every collection.

```
interface SearchCriteria {
  pagination?: Pagination
  filter?: Filter[]
  sort?: Sort[]
  term?: Term
  association?: Association[]
  aggregation?: Aggregation[]
  totalCountMode?: TotalCountMode
}

```

**Limit and page**
```
interface Pagination { 
  limit: number
  page: number
}
```

**Filter**
behaves as a term filter
```
interface Filter {
  field: string # depends on the entity Type.
  value: any # or only primitive types
}

# to consider: should have param converter function which translates it into a specific output in the request like filter[<entity>field]=value
```
other filters available in shopware but not documented on API side:

- EqualsAnyFilter
- EqualsFilter
- ContainsFilter
- RangeFilter
- ScoreQuery
- 

**Sort**

```
interface Sorting {
  field: string # depends on the entity Type. could be a nested field as well: visibilities.id
  direction: string # asc || des
}

# depending on the entity's type, the only sortable field should be covered
```

**Search**

```
interface Term {
  name: string
}
```

**Associations**
include related entity by providing a path. Can be used as an array of associations
```
interface Association {
  name: string # for instance product.media.url or something nested
  filter?: Filter[] # nested filter on association
}
```

**Aggregations**
Allows you to gather statistical data about your executed query
Aggregates the result of specific type on specific field, for instance shows the amount (count) of all categories used in returned products' collection
```
interface Aggregation {
  name: string # name of the aggregation
  type: string # count , avg, max, min, stats, sum, filter, entity, terms, histogram
  field: string 
}
```
**Total count mode**
The total count mode allows you to configure the value of the `total` property of the result.
```
interface TotalCountMode {
  mode?: string # exact, next_pages, none (default)
}
```

**Comment by patzick** [comment]
My question and notes :)

### SearchCriteria
Nice to have pagination separated 👍

I'm wondering about separated sort. Isn't it kind of filter as well?
For example, the user goes to category page `/some-category?color=red&color=ping&page=4&sort=price_desc` or something similar
having separated filters and sort requires additional logic to recognize them; couldn't we merge that somehow?
Same thing about the Term - how does it look like? Couldn't be the filter as well?

And now I think also with pagination - maybe this could also be the Filter?

### Filter
Can we filter over every Entity field?
The value should probably to be `string | string[]`.
We need to think if someone has 10 productIds and want's to load them he would need to create 10 Filters or one with 10 values. Or maybe it could be resolved by another type of filter, just wondering here ;)

### Sort
The first note is, like in SearchCriteria about Sort as a Filter
the direction could be an Enum, but not sure now.

### Associations
Which associations by default are included?

### Aggregations
are they showed beside `total` field in response?
the type could be an enum.

### Total count mode
The first idea is to have ResponseOptions interface and TotalCoundMode could be an Enum, not an interface



Nice proposition, please remember to add these comments, best with usage example to docs of interfaces :)
