### ISSUE TITLE
Create Category Service Interface

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#56]
Category service should be using a Connection layer (based on axios library).
Each method of the service will contain specific types of parameters and return typed data (corresponding to data models' interface - #42 )

_It's assumed that the context token is provided on request layer._

### The proposed list of methods:
1. `searchIds(params): <SearchResult<string|uuid[]>` || `findIds(params): <SearchResult<string|uuid[]>` - search only for category ids for specific query
2. `find(params): <Category>` || `findOne(params): <Category>` - fetch the chosen category details
3. `findAll(params):<SearchResult<Category[]>` || `list(params):<SearchResult<Category[]>`- get the list of all categories fit all parameters passed

All the parameters should be converted into query string (or payload) just before sending a request. 
Params converter was described here: #58 

_SearchCriteria interface_ described in #55 

### Parameters:
 Ad. 1. 
```
interface searchIdsParams extends SearchCriteria {
}
```
Ad. 2.
```
interface findParams {
  id: string # or uuid interface if any
}
```

Ad. 3. 
```
interface findAllParams extends SearchCriteria {
}
```

### The list of fields that can be used in the filter or sorting queries within the category:
```
id: string | uuid
afterCategoryId: string | uuid
parentVersionId: string | uuid
mediaId: string | uuid
displayNestedProducts: number # 1 if true, 0 otherwise
autoIncrement: number
level: number
path: string
type: string # page, link, folder
visible: number # 1 if true, 0 otherwise
active: number # 1 if true, 0 otherwise
name: string
cmsPageId: string | uuid
```

**Comment by patzick** [comment]
1. What's the use case for this method?

2. and 3. i'd be for some kind of naming conventions like
- `getCategory, getCategories`
- `fetchCategory, fetchCategories` (my personal favourite, IMO most accurate)
- `findCategory, findCategories`
- `loadCategory, loadCategories`

2 and 3 should also have the same params. Method which returns single object should just add `limit=1` to filters and cast result Array to an Object.

**Comment by rmakara** [comment]
Using entity names in methods like fetchCategory, fetchCategories seems to be easier solution for using it instead of category.findId, category.findIds.

We need to keep in mind that for Category pages there is also cms content to display in each page. There are fields `cmsPageId` and `cmsPage` in `CategoryInterface`. At some point we should think about handling that with single getCategory method or two getCategory and getCmsPage methods.

If getting `Category.cmsPage` works (I am not sure) just like `product.associations[]` param in Product endpoints then we must clarify, that we want to load `cmsPage` nested object when asking Shopware for a category.

**Comment by mkucmus** [comment]
> 1. What's the use case for this method?

 It behaves the same as the search does, but the response is super light and contains only the ids of the documents you found regarding search criteria you just provided. Not sure if we need it on this scope. But in general, it should cover the public SW API Interface and you can't forget about this method as well.
> 2. and 3. i'd be for some kind of naming conventions like
> 
> * `getCategory, getCategories`
> * `fetchCategory, fetchCategories` (my personal favourite, IMO most accurate)
> * `findCategory, findCategories`
> * `loadCategory, loadCategories`
`fetchCategory, fetchCategories` (my personal favourite, IMO most accurate)

Seems to be a good one. I proposed the naming with some kind of abstraction layer, so you could guess the entity you are finding/fetching from the name of the service, but It's totally ok to use categoryService.fetchCategories().


> 2 and 3 should also have the same params. Method which returns single object should just add `limit=1` to filters and cast result Array to an Object.

I should have pasted some good sample which ponits the differences between 2 and 3. 
So, the 2, should only take id param, its like fetching the entity you've already known -> /product/1234
3rd is a standard listing query.
