### ISSUE TITLE
[BUG] init script does not run on VM 

### ISSUE THREAD

**Issue by ivosanchez** [DivanteLtd/shopware-pwa#560]
I can run the whole demo in a mac with catalina, but init cli script does not run in bitnami-shopware VM on linux, nor bitnami on docker on linux. It  says it cannot find npx. Maybe an issue with nuxt  install routines as in (( Reference :https://github.com/nuxt-community/starter-template/issues/48 }} 

✔ Shopware instance address: · https://shopware-2.vuestorefront.io
✔ Shopware instance access token: · SWSCMUDKAKHSRXPJEHNOSNHYAG
✔ Shopware admin username: · admin
✔ Shopware admin password: · *****
⠴ Preparing Nuxt project/usr/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Command failed: npx --ignore-existing create-nuxt-app --answers "{\"name\":\"shopware-pwa-project\",\"description\":\"shopware-pwa-project description\",\"author\":\"Vue Storefront\",\"pm\":\"yarn\",\"ui\":\"none\",\"language\":\"js\",\"server\":\"none\",\"features\":[\"axios\",\"pwa\"],\"linter\":[\"prettier\",\"lintStaged\"],\"test\":\"jest\",\"mode\":\"universal\",\"devTools\":[]}"
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/16184/lib/node_modules/create-nuxt-app/node_modules/ejs/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ejs@2.7.4 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ejs@2.7.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-28T15_30_59_756Z-debug.log
Install for create-nuxt-app@latest failed with code 1

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
root@debian:/opt/bitnami/apps/shopware/shopware-pwa# npm i -g create-nuxt-app

**Comment by patzick** [comment]
thanks for issue @ivosanchez, could you please provide CLI version as well?
to check it type: `shopware-pwa --version`

**Comment by ivosanchez** [comment]
hi. 
0.1.0-alpha.4

**Comment by patzick** [comment]
hey @ivosanchez , could you try to repeat the process with canary version?
It's package always published from the current master, you can install it typing `npm i -g @shopware-pwa/cli@canary`
when we solve that issue we'll release it as a next version

**Comment by patzick** [comment]
@ivosanchez please reopen the issue if it's still a problem
