### ISSUE TITLE
Create Product Service Interface

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#57]
Product service should be using a Connection layer (based on axios library).
Each method of the service will contain specific types of parameters and return typed data (corresponding to data models' interface - #41  )

_It's assumed that the context token is provided on request layer._

### The proposed list of methods:
1. `searchIds():<SearchResult<Product[]>` || `findIds():<SearchResult<Product[]>` - search only for category ids for specific query
2. `find():<Product>` || `findOne():<Product>` - fetch the chosen category details
3. `findAll():<SearchResult<Product[]>` || `list():<SearchResult<Product[]>` - get the list of all categories fit all parameters passed

All the parameters should be converted into query string (or payload) just before sending a request.
Params converter was described here: #58

_SearchCriteria interface_ described in #55 

### Parameters:
 Ad. 1. 
```
interface searchIdsParams extends SearchCriteria {
}
```
Ad. 2.
```
interface findParams {
  id: string # or uuid interface if any
}
```
Ad. 3.
``` 
interface findAllParams extends SearchCriteria {
}
```

### The list of fields that can be used in the filter and sorting queries within the product area:
```
id: string | uuid
parentVersionId: string | uuid
mediaId: string | uuid
autoIncrement: number
visible: number # 1 if true, 0 otherwise
active: number # 1 if true, 0 otherwise
stock: number
availableStock: number
displayGroup:  string | uuid
manufacturerId: string | uuid
unitId: string | uuid
taxId: string | uuid
coverId: string | uuid
price: number
manufacturerNumber: string
ean: string
productNumber: string | uuid
isCloseout: # 1 if true, 0 otherwise
purchaseSteps: number
maxPurchase: number
minPurchase: number
purchaseUnit: number
referenceUnit: number
shippingFree:  # 1 if true, 0 otherwise
purchasePrice: number
markAsTopseller:  # 1 if true, 0 otherwise
weight: number
width: number
height: number
length: number
releaseDate: date

```

**Comment by patzick** [comment]
Pretty related comment in https://github.com/DivanteLtd/shopware-pwa/issues/56#issuecomment-540924443

**Comment by mkucmus** [comment]
Ok, just follow the discussion from #56 and we are going to apply the rules from that discussion.

**Comment by mkucmus** [comment]
> searchIds():<SearchResult<Product[]> || findIds():<SearchResult<Product[]> - search only for category ids for specific query

`getProductIds()` will be used
> find():<Product> || findOne():<Product> - fetch the chosen category details

`getProduct()` will be used
> findAll():<SearchResult<Product[]> || list():<SearchResult<Product[]> - get the list of all categories fit all parameters passed

`getProducts()` will be used
