### ISSUE TITLE
[BUG] Advanced pricing / Rule Builder

### ISSUE THREAD

**Issue by sawden** [DivanteLtd/shopware-pwa#570]
I am using the Rule Builder included in Shopware 6, to calculate a specific product price with a custom rule I created in the administration area. The rule is working perfectly in the default storefront, but the PWA storefront seems to have an issue here.

**Is this a bug or are the pricerules not supportet right now?**

My rule used for this example:
- if product width is bigger than 1200cm and Quantity is 1-2 = price is £5000
- if product width is bigger than 1200cm and Quantity is 3-∞ = price is £10

![issue](https://user-images.githubusercontent.com/36924392/77939229-22ffea00-72b7-11ea-8680-99a4da32afe2.png)

**Comment by patzick** [comment]
@sawden is it still an issue?
Corrected price should be displayed.

@akrajna please check that case on demo instance.

**Comment by sawden** [comment]
It is still an issue.

_Tested with "shopware 6.2" and "shopware-pwa v0.1.0-alpha.7"._

💙💚

**Comment by mkucmus** [comment]
duplicated by #1150 will be fixed within the mentioned issue.
