### ISSUE TITLE
[BUG]Problem with scrolling during registration on iOS 

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#591]
### Describe the bug
On iOS during registration there is a problem with:
A. scrolling to the place where 'Don't have and account yet? Register today? ' is written on smaller resolution like iPhone 8
B. scrolling through the registration form in order to press the 'Create an account' button on bigger resolution like iPhone XS. 

**How to reproduce**

case A:
1. Go to Home page on iPhone 8
2. Press the login icon
3. Try to scroll down tho the place where 'Don't have and account yet? Register today? ' is written
4. See the error
case B:
1. Go to Home page on iPhone XS
2. Press the login icon
3. Press 'Register today'
4. Try to scroll down to the place where, 'Create an account' button is.
5. See the error

**Expected behavior**
It is possible to scroll down during registration on iOS

**Actual behavior**
It is not possible to scroll down during registration on iOS

**Screenshots**
case A:
 ![RejestracjaiOS](https://user-images.githubusercontent.com/57936972/78146000-de4c8e00-7431-11ea-8f87-ccfdf707a2ef.gif)

case B
![RegistrationFormMobile](https://user-images.githubusercontent.com/57936972/78662878-7e426580-78d1-11ea-96d5-fb4719a15659.gif)

**Devices (please complete the following information):**
iOS 

Tested on browserstack

**Comment by patzick** [comment]
done with #595 , @akrajna please reopen if not fixed

**Comment by ranjan1975** [comment]
The problem still exists. Am not able to register as page doesn't scroll up and you can access the buttons below.

**Comment by niklaswolf** [comment]
We see this problem too, see #1665
