### ISSUE TITLE
[FEATURE] Add search with menu at the bottom of the & page on mobile [Est. 2]

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#592]
### Description
Add 'search' at the bottom of the screen on mobile devices so that the user does not have to take their hands off the screen.
According to the design:
![Zrzut ekranu 2020-04-7 o 15 24 05](https://user-images.githubusercontent.com/57936972/78674782-6cb68900-78e4-11ea-8dbf-2fd006f1bc3d.png)

Refers to the issue: https://github.com/DivanteLtd/storefront-ui/issues/975 

### Acceptance criteria

- [ ] after pressing the 'menu/search' icon on mobile the menu with search is opened as shown on the picture above

**Comment by mkucmus** [comment]
It's already done within #1135
