### ISSUE TITLE
[BUG] Issue with duplicate filter options

### ISSUE THREAD

**Issue by brianantonelli** [DivanteLtd/shopware-pwa#599]
If the same filter option exists within two filters, when checking the option in the second filter it will be selected in the first filter instead.

# Steps to Reproduce:

## SW Admin Console
1. Create a property called: "One" with options: "Foo", "Bar", "Baz"
2. Create a property called "Two" with options: "Foo", "Bar", "Baz"
3. Apply property/option for "One" and "Two" to a product

## PWA Instance
1. Click Filters
2. Click "Foo" under "Two" and "Foo" will be selected under "One"

**Comment by mkucmus** [comment]
The issue seems to disappear after one of storefront-ui upgrades.
On the request layer, the option values are fine as well - so UI and client layer works fine. 
@brianantonelli have you tried to update shopware-pwa instance?

**Comment by patzick** [comment]
closing as probably already resolved :)
@brianantonelli please let us know if you have problems after update
