### ISSUE TITLE
[FEATURE] Implement new designs for checkout

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#602]
### Description

Implementation of new designs

![image](https://user-images.githubusercontent.com/13100280/79227621-7a2dbf00-7e60-11ea-82c8-ba22c782e49b.png)
![image](https://user-images.githubusercontent.com/13100280/79227738-a5b0a980-7e60-11ea-88da-e09ecdcd3cff.png)

### Acceptance criteria

- [ ] new designs are applied to the theme without changing the flow of the checkout

**Comment by martaradziszewska** [comment]
@patzick I think this issue is related to #595 and it was done in PR #645

**Comment by patzick** [comment]
right, closing this one :)
