### ISSUE TITLE
[FEATURE] Show shipping methods in checkout

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#603]
Display proper shipping options
![image](https://user-images.githubusercontent.com/13100280/79228196-54ed8080-7e61-11ea-8c19-e2d125c67dad.png)

### Acceptance criteria

- [ ] use getShippingMethods from useCheckout in shipping step to show available methods
- [ ] use `setShippingMethod` and `shippingMethod` from `UseSessionContext`

**Comment by mkucmus** [comment]
it's already done
