### ISSUE TITLE
[FEATURE] Show payment methods in checkout

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#604]
### Description

Similar to #603 

![image](https://user-images.githubusercontent.com/13100280/79228377-9847ef00-7e61-11ea-8763-df5c3e201c44.png)

### Acceptance criteria

- [ ] methods like in #603
- [ ] extend interfaces of useCheckout and useSessionContext if necessary

**Comment by mkucmus** [comment]
it's already done
