### ISSUE TITLE
Fill CustomField interface with the fields

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#61]
**Context**
Right now CustomField interface is empty. We want to fill it based on the knowledge from Shopware 6 sources.

**Acceptance criteria**
* `CustomField` interface contains the same fields as original CustomField in Shopware 6.

**Comment by rmakara** [comment]
@mkucmus 
Is it done in #107  and #110  ? :)

**Comment by mkucmus** [comment]
CustomField interface is not being used. Can be closed.
