### ISSUE TITLE
[BUG]Order summary - two links to edit one section

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#616]
### Describe the bug
There are two links to edit one section on desktop view.

**How to reproduce**

1. Go to any category page
2. Add any product to the cart
3. Click on the cart icon in the header
4. Click 'Go to checkout' button
5. Fill in personal details, shipping, payment and go to review
6. See the error

**Expected behavior**
There is one link to edit one section in Review
<img width="630" alt="ReviewEditFigma" src="https://user-images.githubusercontent.com/57936972/79539962-9fe8dd00-8087-11ea-9080-c920cf65b3e8.png">

**Actual behavior**
There are two links to edit one section in Review 

<img width="628" alt="ReviewEdit" src="https://user-images.githubusercontent.com/57936972/79539881-7760e300-8087-11ea-97df-0f7c2ae2a746.png">

**Comment by patzick** [comment]
closed by #645
