### ISSUE TITLE
[PayPal] Make up the right place of storing the plugin

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#623]
Acceptance criteria:
- [x] It's assumed that is one place to store such thing as a plugin (nuxt plugin / SW6 plugin)
[ ] - there is an interface of that kind of plugin with: 
- library to be imported <some slots for importing scripts>  (could be in the same component if payment plugin is a standalone one)
- configuration for possible modes: sandbox, production, and corresponding credentials
[ ] - the strict structure of files is described

**Comment by mkucmus** [comment]
We decided that the SW6 pwa part of the plugin is the right place of storing such logic. We just need to find out how to generate slots for the payment plugins. A related Issue is created.

**Comment by CthulhuDev** [comment]
Will this implementation be some sort of blueprint for next plugins implementations? In which cases should we put business logic in the pwa part of SW6 plugin and in which other cases should we call plugins API endpoints?

**Comment by mkucmus** [comment]
> Will this implementation be some sort of blueprint for next plugins implementations? In which cases should we put business logic in the pwa part of SW6 plugin and in which other cases should we call plugins API endpoints?

Yes, it will be some kind of template for next implementations.
Basically we should treat PWA (vue) components like twig templates with minimum logic.
DAO is still on the server side.
So, some assumptions will come up after the first plugin implementation (paypal case), for instance:
- consistent endpoint prefix for endpoints that are called from the pwa components (and shopware-pwa/shopware-6-client will only have methods: get, post, patch, etc prefixed under the hood to interact with all the controllers from the pwa plugin - it's not agreed yet, just RFC)
