### ISSUE TITLE
[PayPal][API] Add a controller to handle onApprove callback logic [SPB checkout]

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#628]
blocks #629 
Acceptance criteria:
- [ ] the endpoint URL is described and used by method call within onApprove method done via #626 
- [ ] controller accepts only the paymentID and payherID params.
- [ ] the result of the controller is order bound to the captured payment (paymentID and payerID ids)
- [ ] the SwagPayPal plugin is extended

**Comment by mkucmus** [comment]
[it covers smart buttons checkout]

Since the approach has changed we realize it's easiest to extend the SwagPayPal plugin with Pwa extension. I've made a draft of it at https://github.com/mkucmus/SwagPayPalPwa.


I've also described our needs to make the Smart Buttons work on shopware-pwa at https://github.com/mkucmus/SwagPayPalPwa/blob/master/src/Controller/PwaController.php
The general idea is to provide 3 endpoints to interact with the SW6 API from the pwa components within the paypal-related checkout. 

The major differences are:
- add an endpoint to get the corresponding client-id (sales-channel can have it's own)
- an endpoint to store transaction data and use it in further order/cart processing.
- add another route for SPB checkout to be reachable from the client.

@elkmod please have a look, especially at https://github.com/mkucmus/SwagPayPalPwa/blob/master/src/Controller/PwaController.php and see the comments in the actions. Any feedback is appreciable :+1:. We will decide how to make it work the easiest and cleanest way :)

**Comment by patzick** [comment]
closed by #679
