### ISSUE TITLE
[FEATURE] Transfer old shopware integration to this repo

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#637]
### Description

Here's the old integration repo: https://github.com/DivanteLtd/shopware2vuestorefront
It should be in read-only mode with a clear message with a link to this repo.

### Acceptance criteria

- [ ] change readme.md file in the old repo with info and link
- [ ] archive repo for read-only state

**Comment by mkucmus** [comment]
It's done.
