### ISSUE TITLE
Create Cart service interface

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#64]
Cart service should be using a Connection layer (based on axios library).
Each method of the service will contain specific types of parameters and return typed data, described in this issue on the bottom.

_Custom cart Interfaces listed at the bottom of the issue._

_It's assumed that the context token is provided on request layer._

### The list of proposed methods:
```
1 getCart(ExtraTokenParam?):CartResponse<Cart> # Cart interface taken from Cart.ts; creates a new one if doesn't exist
2 createCart(ExtraTokenParam?): CartResponse<Cart>
3 addProduct(addProductToCartParam, ExtraTokenParam?):CartResponse<Cart>
4 addCode(PromotionCodeParam, ExtraTokenParam?): CartResponse<Cart>
5 addLineItem(AddLineItemParam): CartResponse<Cart>
6 removeLineItem(RemoveLineItemParam): CartResponse<Cart>
7 updateLineItem(UpdateLineItemParam,ExtraTokenParam?): CartResponse<Cart>
```

**All the parameters should be converted into query string (or payload) just before sending a request.**
Customer Params converter was described here: #TODO

### Available parameters:
```
interface ExtraTokenParam {
  token?: string
  name? : string
}
```

```
interface addProductToCartParam {
  productId: string | uuid
  quantity: number
}
```

```
interface PromotionCodeParam {
  code: string
}
```

```
interface AddLineItemParam {
  itemId: string | uuid
  quantity?: number
}
```

```
interface RemoveLineItemParam {
  itemId: string | uuid
}
```

```
interface UpdateLineItemParam {
  itemId: string | uuid
  quantity: number
}
```

### The list of Cart's custom interfaces:

interface CartResponse<T> { # decide if using the global one is needed
 data: <T>
}

### Method to endpoint map
```
1 getCart() - GET /sales-channel-api/v{version}/checkout/cart
2 createCart() - POST /sales-channel-api/v{version}/checkout/cart 
3 addProduct() - POST /sales-channel-api/v{version}/checkout/cart/product/{id}
4 addCode() - POST /sales-channel-api/v{version}/checkout/cart/code/{code}
5 addLineItem() - POST /sales-channel-api/v{version}/checkout/cart/line-item/{id}
6 removeLineItem() - DELETE /sales-channel-api/v{version}/checkout/cart/line-item/{id}
7 updateLineItem() - PATCH /sales-channel-api/v{version}/checkout/cart/line-item/{id}
```

**Comment by mkucmus** [comment]
@patzick @rmakara  After a quick chat with Dominic, we can postpone handling the other CartItem's types. We stay with the "product" so we can hide the `addLineItem` method (when the type is required) and expose only the `updateLineItem` in order to have a happy path done basing only on product type.

**Comment by patzick** [comment]
@mkucmus that's great, let's just stay with `cartItem` instead of `lineItem` as is more descriptive :)
