### ISSUE TITLE
[FEATURE] Remove triangles icons from Sort By

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/shopware-pwa#656]
### Description

It is better to implement more descriptive label for sorting e.g: Price Low to High or Price ascending / descending 
![image](https://user-images.githubusercontent.com/34887212/80351627-f4077480-8872-11ea-8b90-486d3a53fc87.png)

### Acceptance criteria

- [ ] - removed triangle icons
- [ ] - add more descriptive label for sorting

**Comment by patzick** [comment]
- [ ] probably move it from helpers package to theme helpers
