### ISSUE TITLE
[FEATURE] Move Sort By to Filters on mobile

### ISSUE THREAD

**Issue by martaradziszewska** [DivanteLtd/shopware-pwa#658]
### Description
With the new design, sort by has been removed from the navbar on mobile. It should be implemented on Filters on mobile view inside SfAccordion which is related to #657 

![image](https://user-images.githubusercontent.com/34887212/80349855-2663a280-8870-11ea-997e-dbcc26154cdc.png)

### Acceptance criteria

- [ ] Sort by is moved to Filters on mobile

**Comment by mkucmus** [comment]
duplicated by #398
