### ISSUE TITLE
[FEATURE] Add order endpoint to API client and implement view

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#664]
### Description

success page

### Acceptance criteria

- [x] add endpoint from #262 (added via https://github.com/DivanteLtd/shopware-pwa/pull/752)
- [x] implement view using provided endpoint

**Comment by patzick** [comment]
blocked until 6.2 is released

**Comment by mkucmus** [comment]
There is a possibility to get the customer's order by providing only the order ID, but the customer must be logged in - for some reason, even if the customer placed order as a guest - API treats him as a logged-in so there is no reason to be worried about :+1: 

related PR -> https://github.com/DivanteLtd/shopware-pwa/pull/752
