### ISSUE TITLE
[FEATURE][CMS] Create contact form component

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#666]
### Description

Create CMS element for contact form.

### Acceptance criteria

- [ ] implement contact form endpoint in API client #264 
- [ ] Create CMS element for contact form

**Comment by patzick** [comment]
blocked until 6.2 is released

**Comment by Rigo-m** [comment]
Do we have any clue on 6.2 release date?

**Comment by patzick** [comment]
@Rigo-m there already is a RC version released, so should be in upcoming days 
https://www.shopware.com/en/changelog/#6-2-0
