### ISSUE TITLE
[FEATURE] Default theme refactor for small components

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#702]
### Description

Refactor default theme to be able to have the smallest reasonable components to override while implementing the project

### Acceptance criteria

- [ ] chop big default-theme components to smaller parts

**Comment by Rigo-m** [comment]
May I help with this or is this strictly for the core team?

**Comment by patzick** [comment]
@Rigo-m sorry for missing this question. Sure you can help and it would be great:) Keep in mind to have as small changes as possible per PR so to not interfere with other works as there is a lot going on now:) with any questions just ask me on Slack

**Comment by patzick** [comment]
Done as for 0.1.0. We'll be going this way without breaking changes with priority for parts which will be suggested in issues from the community.
