### ISSUE TITLE
include webp format for all images

### ISSUE THREAD

**Issue by theomanus** [DivanteLtd/shopware-pwa#711]
As for page speed reasons all images should be also in webp format.

we cant use a webp compressor in our project, because the images are not in asset folder when deploying the project on server. The images will be loaded via API to the site. So for my understanding either Shopware enables the webp format for api or you guys integrate a webp compression while you load the images from shopware.

**Comment by Rigo-m** [comment]
Images gets retrieved by API, so it should be shopware's media manager job to compress images in webp.
PWA/storefront-ui side, there should be an implementation of the picture tag with sources etc (https://github.com/DivanteLtd/storefront-ui/issues/1042)

Although you can achieve both of these features via plugins/custom cms implementation I think that it should be a built-in feature

**Comment by theomanus** [comment]
I think that shopware won't add the webp format in their media manager. You can achieve that via 3rd party plugin, but then you still have the problem that this "extra" format won't be available via the store-api.

This format should be used on any displayed image, not only in CMS, also especially on product listings and detail pages

**Comment by mkucmus** [comment]
the shopware-pwa itself it's agnostic when it comes to deal with images. We are only a client and have nothing to do with processing and exposing images in specific formats. This is why I'm closing it - perhaps it should be moved to shopware6 repository.
