### ISSUE TITLE
[FEAT] Search

### ISSUE THREAD

**Issue by elkmod** [DivanteLtd/shopware-pwa#741]
### Description
Provide a basic search preview and search result page with further filtering options

### Acceptance criteria
* Typing a term in the search bar will result in a preview of search result with corresponding product information (name, price, cover preview)
* I can select a product and go straight to the detail page (using keys or by clicking)
* I can go to the search result page using `Enter` or by clicking `Show search results` (or similar)
* On the search result page I see my search term and a list of products matching the term
* On search result page I have the same filtering and sorting options as in a category listing that let me specify the criteria of my search result.
* Ability to switch between presentation in result using grid/listing mode

**Comment by patzick** [comment]
Done by #795 , filters and preview will come after this
