### ISSUE TITLE
[BUG] Shopware-pwa init fails on create-nuxt-app

### ISSUE THREAD

**Issue by linushstge** [DivanteLtd/shopware-pwa#748]
### Describe the bug

shopware-pwa init fails on Debian 9, 10 & Ubuntu 18.04

```
[...]
Error: Command failed: npx --ignore-existing create-nuxt-app --answers "{\"name\":\"shopware-pwa-project\",\"description\":\"shopware-pwa-project description\",\"author\":\"Vue Storefront\",\"pm\":\"yarn\",\"ui\":\"none\",\"language\":\"js\",\"server\":\"none\",\"features\":[\"axios\",\"pwa\"],\"linter\":[\"prettier\",\"lintStaged\"],\"test\":\"jest\",\"mode\":\"universal\",\"devTools\":[]}"
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/3897/lib/node_modules/create-nuxt-app/node_modules/ejs/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
[...]
```

1. Clean install of Debian 9, 10 or Ubuntu 18.04
2. Install Yarn, NPM, shopware-pwa (canary)
3. Execute shopware-pwa init

### Additional context

Linux Version: Ubuntu 18.04
Yarn Version: 1.22.4
NodeJS Version: v14.2.0
NPM Version: 6.14.4
Nuxt Version: v2.12.2
Shopware PWA Version: 0.1.0-canary.1054

![shopware-pwa-init-fails](https://user-images.githubusercontent.com/2674751/82187518-d450f280-98ec-11ea-882f-90838ffbc3a7.png)

**Comment by patzick** [comment]
hey @linushstge, this problem should be resolved, could you confirm that?

**Comment by mkucmus** [comment]
issue is obsolete, closing it
