### ISSUE TITLE
remove rejectUnauthorized parameter in api client instance

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#755]
can we get rid of it here? I know what's for, but since we have no problems with certificates and connection between layers - we can go without it.

_Originally posted by @mkucmus in https://github.com/DivanteLtd/shopware-pwa/pull/743_

**Comment by patzick** [comment]
For additional context
![image](https://user-images.githubusercontent.com/13100280/82753652-7ed28500-9dc7-11ea-8e28-9768265775e3.png)
