### ISSUE TITLE
[BUG] Product prices not visible in listing

### ISSUE THREAD

**Issue by elkmod** [DivanteLtd/shopware-pwa#770]
### Describe the bug

Product prices are not visible in listings (probably depending on name length).

### Additional context

![image](https://user-images.githubusercontent.com/7780750/82651310-43e01e00-9c1c-11ea-83c8-3179090e8b84.png)

**Comment by luklus** [comment]
@elkmod Is the problem still present? Unfortunately I can't reproduce the bug, could You please provide additional instructions?

**Comment by mkucmus** [comment]
The issue is not present on the latest stable release. Closing it.
