### ISSUE TITLE
[BUG] npm ERR! Unexpected end of JSON input while parsing near '...nbul":"^1.1.1","gulp-'

### ISSUE THREAD

**Issue by ivosanchez** [DivanteLtd/shopware-pwa#779]
This is now just to let you know, cuz I can install now using an older version of yarn.

On trying to install shopware-pwa- canary 
on catalina 
using node 10.20.1 & npm 
I get 
npm ERR! Unexpected end of JSON input while parsing near '...nbul":"^1.1.1","gulp-'

**Comment by patzick** [comment]
hey @ivosanchez, is this problem still occurs when you're using `npx @shopware-pwa/cli init`?
