### ISSUE TITLE
[BUG]On iOS v10 or less the page is not working correctly

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#780]
### Describe the bug
On iOS v10 or less the page is not working correctly:
* the pictures are not displayed
* the bottom navigation is not working
* the filters are not working
* switch view from grid to horizontal is impossible
* add to cart is not working

### Steps to reproduce:
1. go to homepage, use device with iOS v10 or less
2. See the error

### Additional context
![iOSv10](https://user-images.githubusercontent.com/57936972/82802960-05e33400-9e80-11ea-8450-7659ca1537d4.gif)

**Comment by Malwurf** [comment]
iOS v10 or less is not supported.
