### ISSUE TITLE
[BUG]Product page is not displayed correctly in the horizontal position of the phone

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#782]
### Describe the bug
On Android and iOS in the horizontal position of the phone product page is not displayed correctly:
* the product picture covers some of the information e.g price, add to cart button, rating stars, description.

### Steps to reproduce:
1. go to any product page on mobile 
2. rotate your device into horizontal position
3. see the error

### Additional context
<img width="635" alt="iOsHorizontal" src="https://user-images.githubusercontent.com/57936972/82805045-9ec77e80-9e83-11ea-9cb5-a99206a03c0d.png">

**Comment by pspaczek** [comment]
fixed by #823
![Zrzut ekranu 2020-06-2 o 09 32 12](https://user-images.githubusercontent.com/12138170/83492705-f5e8d700-a4b3-11ea-89c5-cdfd580dbf42.png)

**Comment by akrajna** [comment]
works great
