### ISSUE TITLE
[BUG]Checkout - 'go back to personal details' button is not working

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#786]
### Describe the bug
In checkout on the step 'shipping' the button 'go back to the personal details' is not working

###Steps to reproduce:
1. go to any product page
2. add the product to the cart
3. click on 'cart' icon
4. click on 'go to checkout' button
5. go through the:'Personal details'and 'Shipping' steps by filling in the appropriate fields
6. click on 'go back to the personal details' button
7. see the error 

### Additional context
![personaldetails](https://user-images.githubusercontent.com/57936972/82813424-55802a80-9e95-11ea-9c24-b967bc7f8e6b.gif)

**Comment by mkucmus** [comment]
it's been fixed already. closing it.
