### ISSUE TITLE
[BUG]Currency switch - currency name does not fit in the field

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#788]
### Describe the bug
The 'nkr' currency does not fit in the field. The field should be big enough to fit the whole currency name.

###Steps to reproduce
1. go to homepage
2. click on the 'currency switch' icon in the header
3. see the error

### Additional context
<img width="83" alt="currency" src="https://user-images.githubusercontent.com/57936972/82867303-e3f2bb80-9f2a-11ea-94f5-9e789e0f180c.png">

**Comment by pspaczek** [comment]
@akrajna I think this PR should fix this issues https://github.com/DivanteLtd/shopware-pwa/pull/773

**Comment by pspaczek** [comment]
🙈 ok, I forgot push my changes
