### ISSUE TITLE
Implement faker.js

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#79]
**Context**
We want to start using Faker.js (https://github.com/marak/Faker.js/) for generating fake data in tests.

**Acceptance criteria**
* Faker.js dependency exists in shopware-pwa.
* There is an example in codebase on how to use Faker.js.

**Comment by rmakara** [comment]
@mkucmus as you were the 1st one to use that you may write a quick note on that and close the issue. :)

**Comment by mkucmus** [comment]
> Faker.js dependency exists in shopware-pwa.
faker was installed and it's available under "faker" dependency
> There is an example in codebase on how to use Faker.js.

you can use faker by importing it with `import faker from "faker"` or import only the selected methods which are grouped by functionalities, here is a list of them:

- address
- commerce
- company
- database
- date
- finance
- git
- hacker
- helpers
- image
- internet
- lorem
- name
- phone
- random
- system
- vehicle

real world example taken from the _packages/shopware-6-client/__tests__/services/CustomerService/register.spec.ts_:
``
import { name, address, random, phone, internet } from "faker";

const customerData = {
  salutationId: random.uuid(),
  firstName: name.firstName(),
  lastName: name.lastName(),
  password: internet.password(8),
  email: internet.email(),
  billingAddress: {
    countryId: random.uuid(),
    street: address.streetName(),
    zipcode: address.zipCode(),
    city: address.city(),
    phoneNumber: phone.phoneNumber()
  }
}
``
