### ISSUE TITLE
[BUG]Navigation block is not working

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#790]
### Describe the bug
The side navigation is not working; after clicking on the subcategory the 404 error page appears. The same subcategory is available from megamenu.

###Steps to reproduce the behavior:

1. Go to the category 'Accessories'
2. Click on the subcategory 'Movies' 'See Movies' form the side menu
3. See the error
4. Click on subcategory 'Movies' from the MegaMenu

### Additional context
* subcategory 'Movies' 'See Movies' form the side menu
<img width="798" alt="Accesiories" src="https://user-images.githubusercontent.com/57936972/82789200-361fd800-9e6a-11ea-875f-2de25255388b.png">
* subcategory 'Movies' from the MegaMenu
<img width="843" alt="Accesories1" src="https://user-images.githubusercontent.com/57936972/82789231-40da6d00-9e6a-11ea-95a9-ac24efc1e86e.png">

**Comment by patzick** [comment]
@akrajna can you check in admin panel to see if the configuration of categories is correct and fix it?

**Comment by akrajna** [comment]
@patzik it seems like a programming issue cause the url are diffrent depande on how you acces the subcategory eg. subcategory 'Grocery' form category 'Kids':
1. accessed from MegaMenu url is *shopware-pwa-canary.storefrontcloud.io/**Kids**/Grocery/*
2. accessed form side menu on the main category 'Kids' is *shopware-pwa-canary.storefrontcloud.io/**Kids/Kids**/Grocery/*
So it looks like when user is entering the subcategory from side menu the main category name is appended to the url and as a result it is doubled.

**Comment by patzick** [comment]
you're right, fixing in #802
