### ISSUE TITLE
I want to use Mega Menu for navigation So I can quickly get to nested categories

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#8]
**Context**
Currently, I can use the navigation in the header (SfHeader component) to browse level 0 categories. Also, I can use the left-hand-side category tree in category pages.

Now, I want to use the Mega Menu component to quickly get access to nested categories.

**Acceptance criteria**
* Mega Menu component from Storefront UI is used.
* I can see level = 0 categories.
* I can see level = 1 categories.
* I can see level = 2 categories - TO REFINE / VERIFY.
* When I click on the link to a specific category then I am redirected to the correct one

**Blocks**
* #427 CMS content in mega menu

**Comment by rmakara** [comment]
@patzick @mkucmus 
Long time no see. Would be cool to add mega menu in the next sprints. :)

**Comment by CthulhuDev** [comment]
https://storybook.storefrontui.io/?path=/story/organisms-megamenu--with-sfheader

MegaMenu already has multiple depths. You need to override the default theme and change the props of the megamenu
