### ISSUE TITLE
[BUG]My account - impossible to edit 

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#812]
### Describe the bug
On demo instance it is impossible to edit 'Personal Details' and 'My addresses' in 'My account'.
In 'My addresses' after clinking one on the 'edit' icon nothing happened after pressing second time the 404 error page opens.

### Steps to reproduce:
initial conditions: user is logged in
1. go to My account
2. change user name
3. click 'Save Changes' button
4. see the error
5. click on 'My addresses'
6. click once on the 'Edit' arrow next to any users address
7. see the error
8. click two times on the 'Edit' arrow next to any users address
9. see the error

### Additional context
![My account Edit](https://user-images.githubusercontent.com/57936972/83121067-23a7d780-a0d2-11ea-9879-485361f101aa.gif)

**Comment by patzick** [comment]
closed by #818
