### ISSUE TITLE
[BUG]Order details component on mobile

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#827]
On mobile 'Thank you page' and 'order details in My account'  the order details needs to be adjusted:
* Item and price is mixed and Quantity and amount are mixed it my be confusing for the user
<img width="209" alt="MobileThankYou" src="https://user-images.githubusercontent.com/57936972/82885050-e2ce8800-9f44-11ea-923f-8f941bc49b58.png">
consider figma design  as below:
<img width="117" alt="figmaOrderDetails" src="https://user-images.githubusercontent.com/57936972/82885179-127d9000-9f45-11ea-9e33-c28d93f78b16.png">

### Steps to reproduce:
initial conditions: user is logged in
1. go to any category page
2. add 3 products to the cart
3. go through the checkout steps (Personal details, Shipping, Payment, Review)
4. click 'place my order' button
5. see the 'Thank you' page
6. go to my account
7. click on Order history
8. click on 'Open' next to the order you just made
9. see the 'Order details' page

**Comment by pspaczek** [comment]
@patzick maybe we can do it like on My Account/Review? We can hide quantity selector and use just static number for it?  
mobile:
![Zrzut ekranu 2020-06-2 o 10 08 25](https://user-images.githubusercontent.com/12138170/83496286-297a3000-a4b9-11ea-8842-8a6eca44e79c.png)
desktop:
![Zrzut ekranu 2020-06-2 o 10 08 49](https://user-images.githubusercontent.com/12138170/83496290-2b43f380-a4b9-11ea-977c-c43901cf7942.png)

**Comment by patzick** [comment]
yeah, on placed order we can change quantity selector to static one and reuse these components :)

**Comment by Malwurf** [comment]
I'm closing this issue. A bug from above doesn't exist in the current version.

![Screenshot from 2020-09-24 14-00-15](https://user-images.githubusercontent.com/4071200/94144728-cd755600-fe71-11ea-8dc5-e53addf86618.png)
![Screenshot from 2020-09-24 13-46-48](https://user-images.githubusercontent.com/4071200/94144732-cea68300-fe71-11ea-832b-5f1515868d84.png)
![Screenshot from 2020-09-24 13-46-36](https://user-images.githubusercontent.com/4071200/94144735-cea68300-fe71-11ea-9e0b-26916312ee39.png)
