### ISSUE TITLE
[BUG] Shopware-pwa init fails [Est. 3]

### ISSUE THREAD

**Issue by sgatrip** [DivanteLtd/shopware-pwa#842]
Describe the bug
shopware-pwa init fails on Debian 9, 10 & Ubuntu 18.04

root@bio:/var/www/shopware-pwa# shopware-pwa init
✔ Shopware instance address: · http://167.71.68.121
✔ Shopware instance access token: · SWSCCNVVRDNYZWNTNGT5EHBLUG
✔ Which version you'd like to use: · latest stable (recommended)
⠇ Preparing Nuxt project/usr/local/share/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Command failed: npx --ignore-existing create-nuxt-app --answers "{\"name\":\"shopware-pwa-project\",\"description\":\"shopware-pwa-project description\",\"author\":\"Vue Storefront\",\"pm\":\"yarn\",\"ui\":\"none\",\"language\":\"js\",\"server\":\"none\",\"features\":[\"axios\",\"pwa\"],\"linter\":[\"prettier\",\"lintStaged\"],\"test\":\"jest\",\"mode\":\"universal\",\"devTools\":[]}"
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/21495/lib/node_modules/create-nuxt-app/node_modules/ejs/postinstall.js'

**Comment by patzick** [comment]
hey @sgatrip, is this still an issue?
have you tried to use `npx @shopware-pwa/cli init`?

**Comment by sgatrip** [comment]
you can close it.
Installation and usage of VSF give us headache !

it's too complex and not well documented..

Customer don't want to pay 2 guys for 2 weekd only for demo !
