### ISSUE TITLE
[FEATURE] Footer Navigation

### ISSUE THREAD

**Issue by krasej** [DivanteLtd/shopware-pwa#848]
### Description
The footer should have a navigation with pages that the shop-owner can set. It should look similar to a default Shopware 6.
Footer navigation can be set on sales channel settings, like:
![Screenshot from 2020-07-03 11-04-46](https://user-images.githubusercontent.com/5596960/86452767-14ddc180-bd1d-11ea-8408-f2aa49189f16.png)

### Acceptance criteria

- [ ] Shows the categories that are set under the Footer-Navigation entrypoint for the sales channel
- [ ] extend shopware-6-client with the appropriate method for that
- [ ] extend useNavigation composable or create a new one for footer navigation
- [ ] navigation links should appear in the Footer component
- [ ] can handle nesting and 3-5 main categories.
- [ ] can handle structuring element and link category-types
- [ ] optional collapsable on mobile

**Comment by elkmod** [comment]
Maybe worth considering to move the navigation endpoint to the Store API navigation endpoint (generalization and less dependence on PWA plugin) to fetch `main-navigation` and `footer-navigation`.

**Old**
```
store-api/v1/pwa/navigation
```
**New**
```
store-api/v1/navigation
```

[Documentation of API endpoint `store-api/v1/navigation`](https://docs.shopware.com/en/shopware-platform-dev-en/store-api-guide/navigation?category=shopware-platform-dev-en/store-api-guide)
