### ISSUE TITLE
SfHeaderNavigationItem dependency on SfHeader

### ISSUE THREAD

**Issue by niklaswolf** [DivanteLtd/shopware-pwa#851]
At the moment it is not possible to replace `SfHeader` with an own implementation that is using `SfHeaderNavigationItem` because the latter depends on the former and doesn't get exported from storefront-ui. So in order to use `SfHeaderNavigationItem` it is necessary to use `SfHeader`.

Patryk answered in slack:
`yeah, the problem is that SfHeaderNavigationItem is registered by SfHeader , so replacing SfHeader is breaking that. This is something to improve on the theme side`

**Comment by patzick** [comment]
thanks, @niklaswolf, it will be released with 0.2.0 :)
