### ISSUE TITLE
[BUG] No matching sales channel found.

### ISSUE THREAD

**Issue by paulvanbladel** [DivanteLtd/shopware-pwa#852]
Created an online shop op shopware https://xxxx.shopwaredemo.store/
create new accesstoken in the backend app
module.exports = {
  shopwareEndpoint: "https://xxxx.shopwaredemo.store",
  shopwareAccessToken: "SWSCAXBTYTDNZLRUVTFOSJHSAW",
};
started the dev server on localhost 3000:
getting error
```
 ERROR  [UseSessionContext][refreshSessionContext] {                                                                     17:17:20  
  message: 'No matching sales channel found.',
  statusCode: 412
}


```
When connecting to the standard demo api everything works as expected.

**Comment by mkucmus** [comment]
hi @paulvanbladel - it looks like you have set the wrong shopwareAccessToken.
Shopware6 is looking for a sales channel with a specific access token, like the one you have provided. But there is no sales channel with that token apparently. 

it was explained here: https://shopware-pwa-docs.vuestorefront.io/guide/troubleshooting.html#issues-caused-by-incorrect-configuration

**Comment by patzick** [comment]
closing as resolved, please let us know if it still occurs
