### ISSUE TITLE
[BUG]Mega Menu is not beautiful

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/shopware-pwa#853]
### Describe the bug
The category and subcategory names are displayed to tight. 
There should be:
- bigger spaces between category and subcategory names, 
- category names should be in upper case, 
- the sub-category names should be in one column aligned with the category names
as on designs: 

<img width="508" alt="MegaMenuDesigns" src="https://user-images.githubusercontent.com/57936972/84486725-1415ba80-ac9e-11ea-8c16-2d3ef08f3404.png">

now it looks as below:
<img width="863" alt="MegaMenuTooTight" src="https://user-images.githubusercontent.com/57936972/84487040-7cfd3280-ac9e-11ea-9bc3-bb52de3a9d46.png">

### Steps to reproduce
1. go to home page
2. hoover over categories in header
3. see the error

**Comment by Malwurf** [comment]
I did that task in #906
