### ISSUE TITLE
[BUG] Menu is Broken on Demo Shop

### ISSUE THREAD

**Issue by beardcoder** [DivanteLtd/shopware-pwa#860]
### Describe the bug
If you have many menu items you can not select the correct sub menu

- go to homepage
- hover a menu element

### Additional context
![menu](https://user-images.githubusercontent.com/9371658/84743241-f4d6a000-afb1-11ea-9939-35b1ddc5d9b7.gif)

**Comment by Malwurf** [comment]
@akrajna link to PR -> https://github.com/DivanteLtd/shopware-pwa/pull/906
