### ISSUE TITLE
[BUG] Save for later button without function

### ISSUE THREAD

**Issue by beardcoder** [DivanteLtd/shopware-pwa#864]
### Describe the bug
The visitor sees the button but nothing happens when you use it

- go to article
- Click "Save for later"

### Additional context
![Bildschirmfoto 2020-06-16 um 11 05 14](https://user-images.githubusercontent.com/9371658/84755106-8ac5f700-afc1-11ea-9a97-5a063c705c4f.jpg)

**Comment by akrajna** [comment]
https://github.com/DivanteLtd/shopware-pwa/pull/883

**Comment by patzick** [comment]
closed by #883
