### ISSUE TITLE
[BUG] Add to compare without function

### ISSUE THREAD

**Issue by beardcoder** [DivanteLtd/shopware-pwa#865]
### Describe the bug
The visitor sees the button but nothing happens when you use it

- go to article
- Click "Add to compare"

### Additional context
![Bildschirmfoto 2020-06-16 um 11 07 42](https://user-images.githubusercontent.com/9371658/84755262-bba62c00-afc1-11ea-9924-f5b53b3760a1.jpg)

**Comment by Malwurf** [comment]
It should be resolved in [#864 ](https://github.com/DivanteLtd/shopware-pwa/issues/864)

**Comment by patzick** [comment]
closed by #883

thanks @beardcoder for issues!
