### ISSUE TITLE
[BUG] Description is displayed 2 times

### ISSUE THREAD

**Issue by beardcoder** [DivanteLtd/shopware-pwa#867]
### Describe the bug
If a visitor is on the article detail page, the description is shown twice

- go to article

### Additional context
![Bildschirmfoto 2020-06-16 um 11 19 53](https://user-images.githubusercontent.com/9371658/84756649-5d7a4880-afc3-11ea-9b90-8e91c70ff25f.jpg)

**Comment by akrajna** [comment]
Deleting description from the tab below 'Add to cart' button resulted in no description on mobile at all. On mobile devices there was only one description visible - the one in the tab. After this changes no description will be visible.
Consider deleting the description above 'Add to cart' button.
![MobileNoProductDescription](https://user-images.githubusercontent.com/57936972/85408412-c6823300-b564-11ea-8fe0-7219b02a850b.gif)
