### ISSUE TITLE
Create performance QA check list

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#87]
* Create checklist in some docs folder.
* Run webpack-bundle-analyzer and create a checklist based on that.
* Filip and Piotr recommended to keep max size of js as 300 kB loaded immediately. All the rest lazy loaded.

**Comment by rmakara** [comment]
Initial QA checklist will be added in:
* https://github.com/DivanteLtd/shopware-pwa/issues/111
* https://github.com/DivanteLtd/shopware-pwa/tree/feature/111-create-a-draft-of-a-readme

**Comment by rmakara** [comment]
@akrajna maybe you can take a look at that to prepare some kind of quality checklist for the product? :)

**Comment by akrajna** [comment]
Here is basic checklist, created to organize regression testing, this list should be updated regularly as the project develops: https://docs.google.com/document/d/1Cn-DkPQO2qu9f3570-dzYdNYB2H-v057ViECI84OcYQ/edit?usp=sharing

**Comment by rmakara** [comment]
@akrajna 
Looks great. :) Can we add that to some file in the repository, please? :) After that, we may close the issue. :)

**Comment by patzick** [comment]
@akrajna please move it to markdown file inside `docs` directory `docs/qa-checklist.md` so we can have it there and close issue :)

**Comment by akrajna** [comment]
done in this PR Feat/cypress login test #676
