### ISSUE TITLE
[BUG] sw-context-token not always present

### ISSUE THREAD

**Issue by mmeester** [DivanteLtd/shopware-pwa#872]
### Describe the bug
Somtimes the context token is not always provided during the setup, which makes it impossible to build up a cart.

### Steps to reproduce
- Run nuxt in SPA mode
- Remove all you application storage by chrome devtools 
- Application ->  clear storage -> click on the button “Clear Site data”
- Refresh the page and add items to your cart (have a look if a cookie is set)

**Comment by patzick** [comment]
hey @mmeester , is it still an issue? I cannot reproduce this on canary https://shopware-pwa-canary.storefrontcloud.io/
We changed a bit creation there, so probably this disappeared as well (I'm aware of #873, but as I cannot reproduce that I'm not sure it is still necessary)
I'm leaving this open - please provide once more reproducible path :)

**Comment by mmeester** [comment]
Hi @patzick , I tried to reproduce this but it's kind of hard with my current setup, let's wait until your 0.2.0 release so I can test it on my setup

**Comment by patzick** [comment]
thanks @mmeester , it's released: https://github.com/DivanteLtd/shopware-pwa/releases/tag/v0.2.0 - Please let us know if the problem still exists
