### ISSUE TITLE
[BUG] Add hyperlinks to footer text

### ISSUE THREAD

**Issue by Malwurf** [DivanteLtd/shopware-pwa#917]
### Describe the bug
Texts in footer should be links its projects home pages or GitHub repositories
 **"Made with :heart: by shopware AG & Vue Storefront"**

![Zrzut ekranu 2020-07-1 o 12 38 33](https://user-images.githubusercontent.com/4071200/86234818-cb179e80-bb97-11ea-8ab0-7834d7da236c.png)

**Comment by tom-aniol** [comment]
@Malwurf can you give me source of this screenshot? :)

**Comment by Malwurf** [comment]
Link to PR -> [#922 ](https://github.com/DivanteLtd/shopware-pwa/pull/922)
