### ISSUE TITLE
[BUG] [shopware-6-client] Pagination Limits doesn't match shopware settings

### ISSUE THREAD

**Issue by Rigo-m** [DivanteLtd/shopware-pwa#938]
### Describe the bug

When querying using SearchCriteria interface, Pagination accepts hard-coded enum for the limit property. But that property should be fetched from shopware configuration (see https://vuestorefront.slack.com/archives/CT7AQR695/p1594220779483300?thread_ts=1594201940.476400&cid=CT7AQR695)

**Comment by patzick** [comment]
hey @Rigo-m 
there is no endpoint for loading limits from shopware, hard-coded ones are the same as defaults in shopware.
My proposition is, to have it as API client settings, so at the end, you could set the limits in `shopware-pwa.config.js`
would that be enough for you?

**Comment by Rigo-m** [comment]
I think any solution is viable here. It's not a priority, I just found myself needing only 2 products and it hurt my feelings loading 5 products if I need only 2 :D

**Comment by Rigo-m** [comment]
We are going to need this soon. Just a follow up question: different limits set on shopware-pwa.config.js will have to be mirrored in the shopware backend or will they work regardlessly of the shopware limit configuration?

**Comment by patzick** [comment]
hey @Rigo-m  - shopware 6.3 will solve this issue! :)
the last point - elimination of preconfigured API limits will help us a lot!

![image](https://user-images.githubusercontent.com/13100280/89728357-0fb31700-da2d-11ea-842c-3c093d0ec465.png)

**Comment by patzick** [comment]
closed by #1005
