### ISSUE TITLE
[BUG] Can't override "components/views"

### ISSUE THREAD

**Issue by d3ntastic** [DivanteLtd/shopware-pwa#942]
### Describe the bug

Tried to override the "views/ProductView.vue" file but changes don't work. Other components overrides work like expected (CategoryView.vue doesn't work aswell).

I override the components with `shopware-pwa override`, the file is copied, thats all. When I ran `shopware-pwa override`  on other components the shopware-pwa cli output restarted the generation/building process even without restarting. When I change something in the copied component file (other than views components) the CLI prints "Updated components/{FileName}.vue" and does a really quick building process. The changes are working really well. When I change something in the views/ProductView.vue nothing is printed in the CLI and nothing changes. I removed the file and ran the shopware-pwa override command again but still the same behaviour.

### Additional context

shopware-pwa-cli canary
Generated/initialized the project with the stable version.

**Comment by patzick** [comment]
Hey @d3ntastic !
Is it still an issue? Probably it's already resolved by #843 - please let me know if that's still a case
