### ISSUE TITLE
[CMS] Check and fix full witdh elements

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#954]
## Acceptance criteria
- [x] CMS elements should be able to be displayed full width
- [x] check where to set it in shopware and pass the knowledge to the team
- [x] set some elements in demo site to full width to show this possibility

**Comment by mkucmus** [comment]
Summary:
- full width or boxed can be applied only on section level
How to set up the full width section: https://drive.google.com/file/d/1r8JSsNrnxGybhyWrCktWK3_E-0UWo1qC/view

- Currently, the most of the blocks have elements with fixed max-width css property, so even if it's contained in the full-width secion, it's still with margins on both sides; left and right. 

![Screenshot from 2020-07-23 16-20-00](https://user-images.githubusercontent.com/5596960/88297783-a3cc7100-cd00-11ea-95b0-5bd671f39c19.png)

**Comment by patzick** [comment]
@mkucmus please add this description to Docs as a separate PR 🙏

**Comment by Rigo-m** [comment]
@mckucmus I'm going to create a PR in some minutes just to move the fixed boxed mode width to a css variable, I'll check conflicts with your work asap (sorry, we needed this to be fixed asap)
