### ISSUE TITLE
[FEATURE] Use config file for API client

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/shopware-pwa#972]
### Description

from slack channel discussion:

![image](https://user-images.githubusercontent.com/13100280/88775407-f5538080-d184-11ea-9c34-8c646fdfccb5.png)

### Acceptance criteria

- [ ] using settings to configure API client, for example setting the timeout

**Comment by itsjainrishi** [comment]
Hi @patzick  I was able to extend timeout period by specifying shopwareTimeout option in config file.
