### ISSUE TITLE
[BUG] Overridden components on Windows 10

### ISSUE THREAD

**Issue by fsavina** [DivanteLtd/shopware-pwa#973]
### Describe the bug
Overridden components (SwHeader, SwFooter, etc.) are ignored while developing on Windows 10

### Steps to reproduce:
1. create a customized version of a default component (SwHeader);
2. on Windows the custom component won't be loaded, the default component will be loaded instead.

**Comment by patzick** [comment]
hey @fsavina, sorry for that! You check working version on canary!
Do you need it as a hotfix for stable release?

**Comment by fsavina** [comment]
thanks @patzick, it works like a charm now!
we are working with the canary version so no rush to have it in a stable release
