### ISSUE TITLE
[BUG] Search doesn't work on search result page

### ISSUE THREAD

**Issue by elkmod** [DivanteLtd/shopware-pwa#974]
### Describe the bug

The search doesn't work when you are on the search result page.

**Reproduce:**

Search for some products using the search bar and hit enter (e.g. "linen")

On search result page go to the search bar and search for something else (e.g. "awesome").

It does re-render the listing, however with the old set of results. 

=> https://shopware-pwa.storefrontcloud.io/search?query=linen

**Comment by patzick** [comment]
fixed with #978 will be released today as hotfix 0.2.1
