### ISSUE TITLE
[Ui] Fix the content inside the sections to have no overlapping between the sections

### ISSUE THREAD

**Issue by mkucmus** [DivanteLtd/shopware-pwa#976]
best place to test: /Baby category

Acceptance Criteria:
- [ ] fix the content overlapping
- [ ] each section has it's own space between another one

![image](https://user-images.githubusercontent.com/5596960/88789658-49fff700-d197-11ea-9f22-6a5294961982.png)

**Comment by Malwurf** [comment]
Same as #968
