### ISSUE TITLE
[SPIKE] Recommendation on Available Filters for the Category

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/shopware-pwa#98]
**Context**
One of the key features of category page is filtering. We need to find a way how to get all the available filters for the category and make sure we always display a good filter type for the property. We got information from Shopware Team:

> This should be possible using an entity aggregation on product options in the product endpoint.
> 
> Pseudo:
> 
> * Get products
> * Filter on categoryId equals id
> * Add aggregation for product options within the result set. I assume you have to re-aggregate them on the client-side to get the corresponding property dimensions (they also need a dedicated aggregation)"

**Acceptance criteria**
* Shared insights about getting these filters in a way described above.
* Shared "descission" if the recommended scenario is a good one or not (due to possible performance issues or logical errors).
* In case of not accepting the initial recommendation, giving recommendation on how to solve that issue.
* Explanation of "why in that way" is provided.
* Typescript interface for the endpoint is added to /RFC folder.

**Comment by mkucmus** [comment]
We've got two aspects of attributes: ordinary attribute which keeps value and can be used for variant configuration, it's called "property", and something similar called "custom fields". 
**It's assumed that we are filtering only by properties.**

### 1. proposition of the extra object contained in category's data model interface #52 
proposed _listingConfiguration_ would be a part of each category's returned data.
It aggregates all the properties ready to filter withing the products' collection assigned to the category. It adds some extra information which might be helpful. 

```      "listingConfiguration": { // extra field which contains filtering and sorting. might be named just like "configuration"
        "sorting": [ // array of product's fields available to sort by
          "name",
          "price",
          "isDiscounted"
        ],
        "filtering": [ // array of objects
          {
            "groupId": "3f637f17cd9f4891a2d7625d19fb37c9", // id of the attribute
            "code": "color", // just for internal use - not necessary
            "label": "Color", // displayed label
            "type": "option", // option is default one, all the properties in SW are predefined as an option, it's natural case
            "properties": [ // if type == option should have also an array of objects with values and labels; id corresponds to product.propertyIds value
              {
                "id": "cc921c5fd5e2430ba878fb194c1aeb8a",
                "label": "White"
              },
              {
                "id": "b4921c5fd5e2430ba878fb194c1aeb8v",
                "label": "Black"
              },
              {
                "id": "a2921c5fd5e2430ba878fb194c1aeb8a",
                "label": "Yellow"
              }
            ]
          },
          {
            "groupId": "446306aaa1ae44619dd78ee4a980bdd8", // id of the attribute
            "code": "size",
            "label": "Color", // displayed label
            "type": "option", // option is default one, all the properties in SW are predefined as an option, it's natural case
            "properties": [ // if type == option should have also an array of objects with values and labels; id corresponds to product.propertyIds value
              {
                "id": "cc921c5fd5e2430ba878fb194c1aeb8a",
                "label": "White"
              },
              {
                "id": "b4921c5fd5e2430ba878fb194c1aeb8v",
                "label": "Black"
              },
              {
                "id": "a2921c5fd5e2430ba878fb194c1aeb8a",
                "label": "Yellow"
              }
            ]
          },
          // examples below can't be virtual and not based on aggregated product's data, just on configuration that comes from Shopping Experiences (CMS)
          {
            "groupId": "a2612f17cd9f4891a2d7625d19fb37c9",
            "code": "price",
            "label": "Price",
            "type": "price" // or just type range, and field price
          },
          {
            "groupId": "f913f17cd9f4891a2d7625d19fb37c9",
            "code": "createdAt",
            "label": "New",
            "type": "date"
          }
        ]
      }```

### 2. how to build filtering queries for properties

**// filtering by option**
```
const containsFilter1: ContainsFilter = { // XL size
  "type": "contains",
  "value": "b252ce508047479da6b2493e5f493a0d",
  "field": "propertyIds"
}
```
```
const containsFilter2: ContainsFilter = { // black
"type": "contains",
"value": "1e52ce508047479da6b2493e5f493a0d",
"field": "propertyIds" // all the filters bases on properties (not custom fields)
}

```

**// combine them**
```

const multiFilter: MultiFilter = {
  "type": "multi",
  "operator": "OR", // or AND, XOR
  "queries": [
      containsFilter1,
      containsFilter2
  ]
}
```

### Pros
1. All the heavy operations are done server-side
2. There is a complete list of attributes and variants that can be used for rendering the filters on each category separately


### Cons
1. decide which place would fit better for setting the configuration of possible filters which are not taken from product properties. The built-in fields like price, creation date and so on.

**Comment by patzick** [comment]
just one concern
Let's assume, that we have these filters in pretty URLs, so we'd use labels instead of ids. Then we have:
`/product?color=red&color=green&size=XL&sort=-price`
Where do we get ids? Is there any way to recognise Shopware filters by the label?

**Comment by rmakara** [comment]
To do after planning:
* Create interface in /RFC for that.
* Create sample object in /RFC for that.
* Link RFC in Swag repository.
