### ISSUE TITLE
[BUG] PageResult should contain category too

### ISSUE THREAD

**Issue by hlohaus** [DivanteLtd/shopware-pwa#996]
### Describe the bug

The page result doesn't containt the category enitiy.
https://github.com/DivanteLtd/shopware-pwa/blob/e4c3053e137cf4d02ab5b361ea4860716f356fe0/packages/shopware-6-client/src/services/pageService.ts

It should do that, because the seo information are in it.

**Comment by mkucmus** [comment]
we do not transform the response from the API. It's returned and available as it comes. The  elkmod/SwagShopwarePwa#51 issue was a good idea :+1:
